<a href="https://colab.research.google.com/github/zeeshanahmad54/H-M-Personalized-Fashion-Recommendations/blob/main/CSCI567_team72_H_and_M_fashion_trending.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from IPython.display import HTML, display

def set_css():
  display(HTML('''
  <style>
    pre {
        white-space: pre-wrap;
    }
  </style>
  '''))
get_ipython().events.register('pre_run_cell', set_css)

In [ ]:
!pip install ipython-autotime
%load_ext autotime

Collecting ipython-autotime
  Downloading ipython_autotime-0.3.1-py2.py3-none-any.whl (6.8 kB)
Requirement already satisfied: ipython in /usr/local/lib/python3.7/dist-packages (from ipython-autotime) (5.5.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython->ipython-autotime) (57.4.0)
Requirement already satisfied: pexpect in /usr/local/lib/python3.7/dist-packages (from ipython->ipython-autotime) (4.8.0)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.7/dist-packages (from ipython->ipython-autotime) (1.0.18)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython->ipython-autotime) (0.7.5)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython->ipython-autotime) (2.6.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython->ipython-autotime) (4.4.2)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.7/dist-packages (from ipython->ipython-autotime) (0.8.1)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.7/dist-packages (from ipython->ipython-autotime) (5.1.1)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython->ipython-autotime) (0.2.5)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython->ipython-autotime) (1.15.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect->ipython->ipython-autotime) (0.7.0)
Installing collected packages: ipython-autotime
Successfully installed ipython-autotime-0.3.1
time: 190 Âµs (started: 2022-05-02 10:52:54 +00:00)

In [ ]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.7/dist-packages (1.5.12)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from kaggle) (4.64.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.7/dist-packages (from kaggle) (6.1.2)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from kaggle) (2021.10.8)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.7/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (3.0.4)
time: 4.03 s (started: 2022-05-02 10:52:54 +00:00)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
time: 14.8 s (started: 2022-05-02 10:52:58 +00:00)

In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))
  
# Then move kaggle.json into the folder where the API expects to find it.
!mkdir -p ~/.kaggle/ && mv kaggle.json ~/.kaggle/ && chmod 600 ~/.kaggle/kaggle.json

Saving kaggle.json to kaggle.json
User uploaded file "kaggle.json" with length 68 bytes
time: 12min 52s (started: 2022-05-02 10:53:13 +00:00)

In [ ]:
# from google.colab import files

# uploaded = files.upload()

# for fn in uploaded.keys():
#   print('User uploaded file "{name}" with length {length} bytes'.format(
#       name=fn, length=len(uploaded[fn])))
  
# # Then move kaggle.json into the folder where the API expects to find it.
# !mkdir -p ~/.kaggle/ && mv kaggle.json ~/.kaggle/ && chmod 600 ~/.kaggle/kaggle.json

In [ ]:
import pandas as pd

time: 324 ms (started: 2022-05-02 11:06:06 +00:00)

In [ ]:
customer_df = pd.read_csv("/content/drive/MyDrive/CSCI_567_ML/Data/customers.csv")
article_df = pd.read_csv("/content/drive/MyDrive/CSCI_567_ML/Data/articles.csv")
transaction_df = pd.read_csv("/content/drive/MyDrive/CSCI_567_ML/Data/transactions_train.csv")

images_folder = "/content/drive/MyDrive/CSCI_567_ML/Data/images"

time: 1min 1s (started: 2022-05-02 11:06:06 +00:00)

## Customers

In [ ]:
# customer_id : A unique identifier of every customer
# FN : 1 or missed
# Active : 1 or missed
# club_member_status : Status in club
# fashion_news_frequency : How often H&M may send news to customer
# age : The current age
# postal_code : Postal code of customer

time: 3.34 ms (started: 2022-05-02 11:07:07 +00:00)

In [ ]:
customer_df.head()

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,NaN,NaN,ACTIVE,NONE,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,NaN,NaN,ACTIVE,NONE,25.0,2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,NaN,NaN,ACTIVE,NONE,24.0,64f17e6a330a85798e4998f62d0930d14db8db1c054af6...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,NaN,NaN,ACTIVE,NONE,54.0,5d36574f52495e81f019b680c843c443bd343d5ca5b1c2...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,1.0,ACTIVE,Regularly,52.0,25fa5ddee9aac01b35208d01736e57942317d756b32ddd...

time: 38.8 ms (started: 2022-05-02 11:07:07 +00:00)

## Articles

In [ ]:
# article_id : A unique identifier of every article.
# product_code, prod_name : A unique identifier of every product and its name (not the same).
# product_type, product_type_name : The group of product_code and its name
# graphical_appearance_no, graphical_appearance_name : The group of graphics and its name
# colour_group_code, colour_group_name : The group of color and its name
# perceived_colour_value_id, perceived_colour_value_name, perceived_colour_master_id, perceived_colour_master_name : The added color info
# department_no, department_name: : A unique identifier of every dep and its name
# index_code, index_name: : A unique identifier of every index and its name
# index_group_no, index_group_name: : A group of indeces and its name
# section_no, section_name: : A unique identifier of every section and its name
# garment_group_no, garment_group_name: : A unique identifier of every garment and its name
# detail_desc: : Details

time: 2.89 ms (started: 2022-05-02 11:07:07 +00:00)

In [ ]:
article_df.head()

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,108775015,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,10,White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
2,108775051,108775,Strap top (1),253,Vest top,Garment Upper body,1010017,Stripe,11,Off White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
3,110065001,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,9,Black,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
4,110065002,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,10,White,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."

time: 37.7 ms (started: 2022-05-02 11:07:07 +00:00)

In [ ]:
for col in article_df.columns:
    if not 'no' in col and not 'code' in col and not 'id' in col:
        un_n = article_df[col].nunique()
        print(f'n of unique {col}: {un_n}')

n of unique prod_name: 45875
n of unique product_type_name: 131
n of unique product_group_name: 19
n of unique graphical_appearance_name: 30
n of unique colour_group_name: 50
n of unique perceived_colour_value_name: 8
n of unique perceived_colour_master_name: 20
n of unique department_name: 250
n of unique index_name: 10
n of unique index_group_name: 5
n of unique section_name: 56
n of unique garment_group_name: 21
n of unique detail_desc: 43404
time: 136 ms (started: 2022-05-02 11:07:07 +00:00)

## Transactions

In [ ]:
# t_dat : A unique identifier of every customer
# customer_id : A unique identifier of every customer (in customers table)
# article_id : A unique identifier of every article (in articles table)
# price : Price of purchase
# sales_channel_id : 1 or 2

time: 988 Âµs (started: 2022-05-02 11:07:07 +00:00)

In [ ]:
transaction_df.loc[transaction_df['customer_id'] == customer_df.iloc[0]['customer_id']]
# transaction_df[transaction_df['customer_id'].str.contains("000058a12d5b43e67d225668fa1f8d618c13dc232df0ca")]

,t_dat,customer_id,article_id,price,sales_channel_id
4212358,2018-12-27,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,625548001,0.044051,1
4212359,2018-12-27,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,176209023,0.035576,1
4212360,2018-12-27,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,627759010,0.030492,1
9663224,2019-05-02,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,697138006,0.010153,2
10754876,2019-05-25,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,568601006,0.050831,2
10754877,2019-05-25,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,568601006,0.050831,2
14479578,2019-07-25,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,607642008,0.012695,1
14479579,2019-07-25,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,745232001,0.021169,1
16728347,2019-09-18,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,656719005,0.044051,2
17074660,2019-09-28,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,797065001,0.054220,2
17074661,2019-09-28,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,797065001,0.054220,2
19160879,2019-11-22,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,785186005,0.016932,2
19357364,2019-11-28,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,694736004,0.018288,1
19357365,2019-11-28,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,785710001,0.024407,1
19357366,2019-11-28,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,812683013,0.036593,1
23574620,2020-03-21,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,841260003,0.011508,2
23574621,2020-03-21,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,887593002,0.021593,2
23574622,2020-03-21,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,890498002,0.031763,2
23574623,2020-03-21,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,795440001,0.014390,2
23574624,2020-03-21,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,859416011,0.014390,2
31140481,2020-09-05,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,568601043,0.050831,1

time: 1.82 s (started: 2022-05-02 11:07:07 +00:00)

## Explore Trending step-by-step

In [ ]:
import pandas as pd
import numpy as np
from math import sqrt
from pathlib import Path
from tqdm import tqdm
tqdm.pandas()

N = 12

time: 6.72 ms (started: 2022-05-03 01:16:07 +00:00)

In [ ]:
df_trans = pd.read_csv("/content/drive/MyDrive/CSCI_567_ML/Data/transactions_train.csv",dtype={'article_id': str})

time: 1min 4s (started: 2022-05-03 01:29:15 +00:00)

In [ ]:
df_trans['t_dat'] = pd.to_datetime(df_trans['t_dat'])
df = df_trans[['t_dat', 'customer_id', 'article_id']].sample(100).copy()
last_ts = df['t_dat'].max()

time: 12.4 s (started: 2022-05-03 01:30:20 +00:00)

In [ ]:
df

,t_dat,customer_id,article_id
6867893,2019-03-01,f7baf8f7d0435be63c0a94b07ddfa07ab5cc2a5e133e001323a5e2d8eff0cf1c,0680262001
20191614,2019-12-16,a5230cd414c9718e1735cacc4357096914f9f36fefba8a24b94aa9f1d5699997,0803986011
6294079,2019-02-17,5daca4a44cd1e355dce96a6ae0a6e483a3c92c16f89d37ebaf0e2f83671aa982,0516000044
2162782,2018-11-05,b379a3233c1395197c54e6ca11674b3e23a856531e01b5bf657f64ac9b93630d,0665817001
21032772,2020-01-07,678a749aacb1a5b3faedaf5bc8bc23720cbf618d2ab8d32b9536d9203e1b27e6,0856440001
21184942,2020-01-11,adb59c69cc7e2841741c5e529292c628e1ac19d8b5ca0e078322ad335d4f70c5,0660308001
14860519,2019-07-31,eec7eca2db06856e95638836eecdf4860563bc4e1b20311e604b90c597badc13,0723349001
17234441,2019-09-28,cdcb5ae7187a23a874511becfb9dba028a1fc6ffe85c5e3bde42631574c74902,0678696014
24523061,2020-04-11,a7fbc1eb6472d798b95b3b742c7abb20c73a1b5b4e79a7ebfadb6b4d814cdf63,0759871004
21039707,2020-01-07,a41776ed1a169af3ead7c64932f3f9e7f8042c010f4668292d28ff5ba46bd01b,0836142001
3820590,2018-12-17,c2f0cdda2dc3042ccd9fcd8253fd8e368769840581e40aab1d87a64ff39987e3,0461327001
29065452,2020-07-15,c7e366346a0e8284ae4a7a7c49618d9240077b2bd507837ea7b732f73e394908,0759871025
12129018,2019-06-19,cf7a1056a22451a0eb6f7dd61b925f4a886a4150e99b52b007a18d8318dfbd25,0734236001
9176547,2019-04-23,885ebfa1515a85ba9feb47fa407f10c4c9611235b059fbdacfdb09042a79d7c2,0701229001
26336527,2020-05-26,8f4d9b1db310c83fd04e5540e9eac7e90e999ec011f0caae30957069519db782,0741220004
11353636,2019-06-04,91c6f4f37786556425cc8aea814a20f1a00e2fe9890d8e40b36ef4a9dcf87373,0685448004
26315640,2020-05-26,2f1055deed1fc1d2ea8da13666faeb93f6e9c8f6597e0bc8c552efab213218de,0806248005
13694456,2019-07-11,a9dae6f31cd2feafc0eebe48ba236cc7fadc62287d7e7636c7699259bb3eeef4,0770212001
5597463,2019-01-30,00e1fc813958a3b6b932b1eecba91895bbbeb722752c8486bee500a912125143,0736102002
13388550,2019-07-06,0e90161bc18662657b18dd5ed863cf5e8be27c6c6da1adabff7fbe504447eb62,0772005005
10993310,2019-05-29,6be4f587cdb5997111cc4401e475bb836ce2496d16617a5b1f48d97a80c62498,0752193001
22741224,2020-02-26,445571567813c79aedc3179baa023da67cc87452cd7031cf023f28767e0c2932,0739362001
8414799,2019-04-06,b90a8270c6f10402cca365cddf1e1e9138a07ac19b2fd6b07dfeb921b91976ce,0465655016
24567714,2020-04-11,ed6dbc458d114a5dfbd1f97e33195032b4f2d2a89dd5c81f2fea2bf78b3e7216,0733097008
7161402,2019-03-09,6e0f8a1cb0777d7e6f10688dd0f1e6019f1281f6a54d4b30175870edc530055f,0569986024
20255535,2019-12-18,4d55bba6821c65d765df96fad06504e51e1aada172d70d43c14c0f31ed368194,0660726005
20584658,2019-12-24,99bf05e9c6f163dbb10c9d7d5c371b189dfcc33799e43f2622b03a6a13b63c90,0767317001
111794,2018-09-22,e3fa3038af5d048ba927e93ee544b6a0fe7a14c83bfa645d7d3c3d3afef4c6e2,0622295001
8817704,2019-04-15,f7f39b58a1e54a8539d970280c1d177e0dde7a5840af984425e7baf8daa58618,0680262004
14698324,2019-07-28,e23d51b58780cc241dd4a412f72f82e0876ce41aabd97ae32622484eb6fa61ad,0614854008
26584583,2020-05-30,a7b299f3f2b14efed1ff4a1dd49127627c8649183cb4635f5dee6837c36c89b0,0852614002
29578532,2020-07-28,3b4cffd4376393398d6eeafdd70bfad80d5da6bd092b7b0d9ffb5e59b5a87235,0609598006
20578294,2019-12-24,6e7938c489f593b748740b62482b66cefa9cffe29739d87d48f68e8e78728eb5,0789909001
10563939,2019-05-21,53297251042630e4725ae591a97c3b4ab40f790fd47fe1d382b49ba4867b166f,0768759005
13010197,2019-06-30,35bdc9d61d688a7d5ea59011ccfe0b2ad3a2ffc77d9e007e642e94311e77bfd5,0692709002
11603205,2019-06-09,e43d0f5e178aadbe2346eed4e6969f8352fea3851b13e941e9a17be328559ab8,0541519034
30413708,2020-08-16,aca3fecf77c200bb6bfc69e0a5e77cfc3712d621793eee12b2ad6464853a603b,0554598071
1541252,2018-10-23,2619f506d7b3d126e93212246955550735a370d8fe0bec90c4123540186a88a5,0529012011
31400948,2020-09-11,b409676fb35b4007967fd7ba003f2a84b7a53aaf6f6a0e66249c18d2fc4253b5,0866383004
8614937,2019-04-11,3466e024e649971a9cd2c411b34fa5882648cf6a413a966ede30e53d4a69bb65,0708379002
443900,2018-09-29,34003a0756c38058c50e8eeba4cd2c4c7af433257fa13b7d7b3faf933940a2c7,0651222002
13236633,2019-07-03,873496e698e4ebe48d8b10f456c54991de3a5364def03fd6ba4fa18ec16a4fd1,0596119001
6188815,2019-02-14,a7cbbeafe87a225affd26e94f0ce6b9b26ad9ecf101ca10fe40145daab48bf3c,0408647008
27516534,2020-06-18,d7266b793a0f0d88882d68aaea54ffa1860be8168c78e21b7435631a399659e6,0843793001
25318952,2020-05-02,6d8305f2a289ee508088ac1eb83f794a95f5948451ff220974ff8d93fc65ac08,0837941001
30666892,2020-08-24,0a72cba855e3b0d9723fa1742a539fca40567a1992ab1c6cfbef8713664893a9,0803757004
26832947,2020-06-05,1b41b04ebe7b0b8c3b9811e587b55f5fc2e5b383fb33331715dbf6174803b048,0876053002
19409592,2019-11-28,7d9e67165744216311a7fdc07089d26ed916a3d54d47e628c3eb6c8765795b1c,0792817001
9224237,2019-04-24,3bfe7ae91681659b2bef61b5a57fde18c8e201acc1d86cadd2c36c20c0c46008,0568601006
15612944,2019-08-18,06605e19bbc6edf2ac2909ab92273a83f8f20c1e7e84e001f4f53f1a534a7488,0784113001
6371752,2019-02-19,ba68ce1d1637b17d342ac625cdadd9bf683bb6fa0212bc41715b2ab6da39dee5,0701016001
153154,2018-09-23,c078c63358442f65b6c0ceb302274ced4ad5528f91fc74e42390ecd0daf906bc,0397068012
19617693,2019-11-29,f4ead16535c55e2a3eb9dbea5b81da33be8dbc35c889f5122a660e5d4217b2d3,0681373019
16494653,2019-09-11,56a41440affbc7462615d0725e4c4cf8379d95f8ac9ae1d7747e3500d968306f,0762796004
758383,2018-10-05,4104330b2b0b496b5b2fe94ccbb3e627c799e419bd25090db93a843aea492f65,0662257001
26904467,2020-06-06,a5266b6fbdbf55c135c21e5763c07838f213492b53c3b315121b5386ae3b1687,0678942037
30891305,2020-08-29,65bbbae08f1bf21ac33a8c3f44b7d5e648b0cbbea35f620beceb36084e278474,0904545002
2420463,2018-11-13,3e2ade7d50ad66e98186e9db53832848496bd86c14a58fdf96c51be282e4ca3f,0681916004
10472404,2019-05-19,185d647c0155e22187784f8632408b4509e14c5fedebaa6105594dd86f4a3259,0690713010
22744035,2020-02-26,571abc187ce8fd5c8d69faaf8094eed5ec579b3792eb667b3ebd630ebb670430,0823791006
11402024,2019-06-05,7b676bcb1cec4323b3dda45a48cc47c97147c41a213ec96e44fe0c90e4bb5be9,0672625004
22779133,2020-02-27,39a3eea894d4be0b571d66becb6ad9c01dfbc3d7e3aa7ba3776537e3030759c8,0830784001
21824124,2020-01-30,4c70c9ab75cf2f718a21f4a57daf2ad2c0319b144963b95acedf4c7e833db3e9,0685814047
2248261,2018-11-08,39076c14992fba0d95d6d45f22c2c503963ed8836259d83bdc6b5ecda8d6f2e7,0662888005
10294636,2019-05-16,1f8c94995b8102bfb1fd93cd70d90d8d6d41921165dc3922ae4426c0f86b7b76,0681385003
20122676,2019-12-14,5df1005c60151edc650ed79b58e7d8bbcfb6664674baeac540893ad12ef76bae,0826776001
23871524,2020-03-30,3c0fb1daa5139911bc27a5172cf65811cbb0488b0759b21ea9c861c696b86526,0821115002
10104288,2019-05-11,58e57c3f54acfb8cdcae5939222ddc2a3e29c99dc5d8210f6df88266b6e88b9e,0708478001
10587738,2019-05-21,dfe7e6ce3cde96e4545b5cf1f6c5918e6e74cc2c4a8dceb2501d2210c8997a4f,0695545002
20527189,2019-12-23,5260372611b0d7965e9e37e3fb431d6e348488bd8c7b991006eb01b30a49d370,0733045001
25644308,2020-05-12,3817b8e643dd6f66f48631dea054468744a717b07d05921c1b644103a369c901,0736681007
28840394,2020-07-10,33f27d1a92af3c3b0564eb81650568368807875f4e7bc05ddf7510ed57fdaa16,0691855012
26443764,2020-05-28,5443964aedf0673793b38d78f15a4a0dfc3b64d8aa069c744a2facc0495aa784,0610776001
24838105,2020-04-20,130d41de31ab0f530daf2408972a9cbd1f8b80bf8186144345d87f0afd32cb8e,0850893001
14418498,2019-07-24,80cc7e1ed463f077046a675961a027a8ba759b9e4fdb53d74b3d97f292c332b0,0736218001
3307342,2018-12-02,67048950a088bccf6b7ca8fa8b0a12a47962562f54b3a7c08474b332bb462b77,0396135047
25932993,2020-05-19,2f109864d25ec1ebd3f56d7484a3551125bab7a703ab441767273c0405df62e5,0864928001
22855518,2020-02-29,3a5da2c16f1052476a8601a148c74a36aa2dc3733664e66d07e1e289270970a1,0822115004
31628043,2020-09-18,514d5cc00cf2c8719458da2ea3337f4167d5340a682310d7ad50123d45850739,0933032002
30472817,2020-08-18,8d55b4ba692580d48ce270e78f368fd4231a752f1abbbb03daaecc9c62fbee25,0905507003
30578276,2020-08-21,6dd6306381ffcaa7fe3fd08aebd5ed4d3b547175cd67ae27e2480354cae9823f,0610776083
21082098,2020-01-08,d39d101148eeebdf8cc0d3aaa32acd6743eb223e5bc44a2ba14dfa8aadd5fa47,0782874001
222477,2018-09-25,3e95ffa5e686bbb55acaa1f4449340e3cb8d1946d62378e67d807da4daa41679,0189616006
19578381,2019-11-29,b5705c172b861c6cb9a8aa14619bce17ff154341fdb10897279025cafc3da6a4,0787853005
28881520,2020-07-11,278aa2097e20a94d6e505da37e41dcc5abc76b78bc27c87ea62a0e875036b610,0766495014
23899395,2020-03-30,fce2a81c1f48a2f451b9a7812c85f99911221242ec9c82e4f5a3532413b11490,0848988001
1887921,2018-10-29,818d9e35537115612476357ec4d27f4d045da48a1ffb6df2d76db22540f1669f,0695972003
106192,2018-09-22,930c326188de496d96e1b365b7b41b23ec36a69af600ea2ac6c216ab74a832d4,0529953001
559678,2018-09-30,14e81f0d467b3dcea4ad85453bc0d5f998af31c0da811809a06c18f7fd5d4842,0516903011
28518866,2020-07-03,0a2de6c095c0771aa5bc2153c37938a07e7daa2bdcd159c8b534c779cb58a276,0660497006
30217693,2020-08-11,deb45961e00f511bc24036d489e208aabb5363483389148dd42c508699586799,0716672018
26507672,2020-05-29,62f4234f20f3a53aa5460c0b40ae1d7829b85dffd72bacce9fc7c4afb6231929,0711582001
29923719,2020-08-04,d04835e523ad0a813069e0252ddbf8b70d7d841429e5d8b4e2fc90e2035f314a,0791587009
23471347,2020-03-16,e78a7b0b3ef980f30305112c9aa04f6957864609f8fdef344b3abba8ae54d2d6,0812364005
31221725,2020-09-07,154446b891fe22b1d7b7351ff4c06f08fcda2d170cb95498dcaf91612ded159a,0872537001
3425637,2018-12-06,35c069a2b893fe405b86c89895a00665dc74a5eee2b19b881262beae120d76ac,0678073001
1790744,2018-10-27,a3f5ab13bbf88a2ee1c3ae809a5113ee57ceb904a4d9a9d46aa4c69f6256c1ae,0656065001
26259425,2020-05-25,1c843c9a9555a6715acde32dec39757cfc8562dab3009b3da71af35fedabc34a,0771383002
25512638,2020-05-08,9ef729cd563ba2556d3e2585977104616761009a0f5fd3c2270640aac96e3b86,0575347003
18999981,2019-11-16,1f67c9cd04038bed60dc526f03479b380f579bdec4c5ab756496b6d9abe55dbd,0720125017

time: 21 ms (started: 2022-05-03 01:30:32 +00:00)

In [ ]:
df['ldbw'] = df['t_dat'].apply(lambda d: last_ts - (last_ts - d).floor('7D')) #Last day of billing week, future date 
weekly_sales = df.drop('customer_id', axis=1).groupby(['ldbw', 'article_id']).count()
weekly_sales = weekly_sales.rename(columns={'t_dat': 'count'})

time: 73.6 ms (started: 2022-05-03 01:30:49 +00:00)

In [ ]:
weekly_sales

                       count
ldbw       article_id
2018-09-28 0189616006  1
           0397068012  1
           0529953001  1
           0622295001  1
2018-10-05 0516903011  1
           0651222002  1
           0662257001  1
2018-10-26 0529012011  1
2018-11-02 0656065001  1
           0695972003  1
2018-11-09 0662888005  1
           0665817001  1
2018-11-16 0681916004  1
2018-12-07 0396135047  1
           0678073001  1
2018-12-21 0461327001  1
2019-02-01 0736102002  1
2019-02-15 0408647008  1
2019-02-22 0516000044  1
           0701016001  1
2019-03-01 0680262001  1
2019-03-15 0569986024  1
2019-04-12 0465655016  1
           0708379002  1
2019-04-19 0680262004  1
2019-04-26 0568601006  1
           0701229001  1
2019-05-17 0681385003  1
           0708478001  1
2019-05-24 0690713010  1
           0695545002  1
           0768759005  1
2019-05-31 0752193001  1
2019-06-07 0672625004  1
           0685448004  1
2019-06-14 0541519034  1
2019-06-21 0734236001  1
2019-07-05 0596119001  1
           0692709002  1
2019-07-12 0770212001  1
           0772005005  1
2019-07-26 0736218001  1
2019-08-02 0614854008  1
           0723349001  1
2019-08-23 0784113001  1
2019-09-13 0762796004  1
2019-10-04 0678696014  1
2019-11-22 0720125017  1
2019-11-29 0681373019  1
           0787853005  1
           0792817001  1
2019-12-20 0660726005  1
           0803986011  1
           0826776001  1
2019-12-27 0733045001  1
           0767317001  1
           0789909001  1
2020-01-10 0782874001  1
           0836142001  1
           0856440001  1
2020-01-17 0660308001  1
2020-01-31 0685814047  1
2020-02-28 0739362001  1
           0823791006  1
           0830784001  1
2020-03-06 0822115004  1
2020-03-20 0812364005  1
2020-04-03 0821115002  1
           0848988001  1
2020-04-17 0733097008  1
           0759871004  1
2020-04-24 0850893001  1
2020-05-08 0575347003  1
           0837941001  1
2020-05-15 0736681007  1
2020-05-22 0864928001  1
2020-05-29 0610776001  1
           0711582001  1
           0741220004  1
           0771383002  1
           0806248005  1
2020-06-05 0852614002  1
           0876053002  1
2020-06-12 0678942037  1
2020-06-19 0843793001  1
2020-07-03 0660497006  1
2020-07-10 0691855012  1
2020-07-17 0759871025  1
           0766495014  1
2020-07-31 0609598006  1
2020-08-07 0791587009  1
2020-08-14 0716672018  1
2020-08-21 0554598071  1
           0610776083  1
           0905507003  1
2020-08-28 0803757004  1
2020-09-04 0904545002  1
2020-09-11 0866383004  1
           0872537001  1
2020-09-18 0933032002  1

time: 21 ms (started: 2022-05-03 01:30:52 +00:00)

In [ ]:
df = df.join(weekly_sales, on=['ldbw', 'article_id'])

time: 17.8 ms (started: 2022-05-03 01:30:54 +00:00)

In [ ]:
df

,t_dat,customer_id,article_id,ldbw,count
6867893,2019-03-01,f7baf8f7d0435be63c0a94b07ddfa07ab5cc2a5e133e001323a5e2d8eff0cf1c,0680262001,2019-03-01,1
20191614,2019-12-16,a5230cd414c9718e1735cacc4357096914f9f36fefba8a24b94aa9f1d5699997,0803986011,2019-12-20,1
6294079,2019-02-17,5daca4a44cd1e355dce96a6ae0a6e483a3c92c16f89d37ebaf0e2f83671aa982,0516000044,2019-02-22,1
2162782,2018-11-05,b379a3233c1395197c54e6ca11674b3e23a856531e01b5bf657f64ac9b93630d,0665817001,2018-11-09,1
21032772,2020-01-07,678a749aacb1a5b3faedaf5bc8bc23720cbf618d2ab8d32b9536d9203e1b27e6,0856440001,2020-01-10,1
21184942,2020-01-11,adb59c69cc7e2841741c5e529292c628e1ac19d8b5ca0e078322ad335d4f70c5,0660308001,2020-01-17,1
14860519,2019-07-31,eec7eca2db06856e95638836eecdf4860563bc4e1b20311e604b90c597badc13,0723349001,2019-08-02,1
17234441,2019-09-28,cdcb5ae7187a23a874511becfb9dba028a1fc6ffe85c5e3bde42631574c74902,0678696014,2019-10-04,1
24523061,2020-04-11,a7fbc1eb6472d798b95b3b742c7abb20c73a1b5b4e79a7ebfadb6b4d814cdf63,0759871004,2020-04-17,1
21039707,2020-01-07,a41776ed1a169af3ead7c64932f3f9e7f8042c010f4668292d28ff5ba46bd01b,0836142001,2020-01-10,1
3820590,2018-12-17,c2f0cdda2dc3042ccd9fcd8253fd8e368769840581e40aab1d87a64ff39987e3,0461327001,2018-12-21,1
29065452,2020-07-15,c7e366346a0e8284ae4a7a7c49618d9240077b2bd507837ea7b732f73e394908,0759871025,2020-07-17,1
12129018,2019-06-19,cf7a1056a22451a0eb6f7dd61b925f4a886a4150e99b52b007a18d8318dfbd25,0734236001,2019-06-21,1
9176547,2019-04-23,885ebfa1515a85ba9feb47fa407f10c4c9611235b059fbdacfdb09042a79d7c2,0701229001,2019-04-26,1
26336527,2020-05-26,8f4d9b1db310c83fd04e5540e9eac7e90e999ec011f0caae30957069519db782,0741220004,2020-05-29,1
11353636,2019-06-04,91c6f4f37786556425cc8aea814a20f1a00e2fe9890d8e40b36ef4a9dcf87373,0685448004,2019-06-07,1
26315640,2020-05-26,2f1055deed1fc1d2ea8da13666faeb93f6e9c8f6597e0bc8c552efab213218de,0806248005,2020-05-29,1
13694456,2019-07-11,a9dae6f31cd2feafc0eebe48ba236cc7fadc62287d7e7636c7699259bb3eeef4,0770212001,2019-07-12,1
5597463,2019-01-30,00e1fc813958a3b6b932b1eecba91895bbbeb722752c8486bee500a912125143,0736102002,2019-02-01,1
13388550,2019-07-06,0e90161bc18662657b18dd5ed863cf5e8be27c6c6da1adabff7fbe504447eb62,0772005005,2019-07-12,1
10993310,2019-05-29,6be4f587cdb5997111cc4401e475bb836ce2496d16617a5b1f48d97a80c62498,0752193001,2019-05-31,1
22741224,2020-02-26,445571567813c79aedc3179baa023da67cc87452cd7031cf023f28767e0c2932,0739362001,2020-02-28,1
8414799,2019-04-06,b90a8270c6f10402cca365cddf1e1e9138a07ac19b2fd6b07dfeb921b91976ce,0465655016,2019-04-12,1
24567714,2020-04-11,ed6dbc458d114a5dfbd1f97e33195032b4f2d2a89dd5c81f2fea2bf78b3e7216,0733097008,2020-04-17,1
7161402,2019-03-09,6e0f8a1cb0777d7e6f10688dd0f1e6019f1281f6a54d4b30175870edc530055f,0569986024,2019-03-15,1
20255535,2019-12-18,4d55bba6821c65d765df96fad06504e51e1aada172d70d43c14c0f31ed368194,0660726005,2019-12-20,1
20584658,2019-12-24,99bf05e9c6f163dbb10c9d7d5c371b189dfcc33799e43f2622b03a6a13b63c90,0767317001,2019-12-27,1
111794,2018-09-22,e3fa3038af5d048ba927e93ee544b6a0fe7a14c83bfa645d7d3c3d3afef4c6e2,0622295001,2018-09-28,1
8817704,2019-04-15,f7f39b58a1e54a8539d970280c1d177e0dde7a5840af984425e7baf8daa58618,0680262004,2019-04-19,1
14698324,2019-07-28,e23d51b58780cc241dd4a412f72f82e0876ce41aabd97ae32622484eb6fa61ad,0614854008,2019-08-02,1
26584583,2020-05-30,a7b299f3f2b14efed1ff4a1dd49127627c8649183cb4635f5dee6837c36c89b0,0852614002,2020-06-05,1
29578532,2020-07-28,3b4cffd4376393398d6eeafdd70bfad80d5da6bd092b7b0d9ffb5e59b5a87235,0609598006,2020-07-31,1
20578294,2019-12-24,6e7938c489f593b748740b62482b66cefa9cffe29739d87d48f68e8e78728eb5,0789909001,2019-12-27,1
10563939,2019-05-21,53297251042630e4725ae591a97c3b4ab40f790fd47fe1d382b49ba4867b166f,0768759005,2019-05-24,1
13010197,2019-06-30,35bdc9d61d688a7d5ea59011ccfe0b2ad3a2ffc77d9e007e642e94311e77bfd5,0692709002,2019-07-05,1
11603205,2019-06-09,e43d0f5e178aadbe2346eed4e6969f8352fea3851b13e941e9a17be328559ab8,0541519034,2019-06-14,1
30413708,2020-08-16,aca3fecf77c200bb6bfc69e0a5e77cfc3712d621793eee12b2ad6464853a603b,0554598071,2020-08-21,1
1541252,2018-10-23,2619f506d7b3d126e93212246955550735a370d8fe0bec90c4123540186a88a5,0529012011,2018-10-26,1
31400948,2020-09-11,b409676fb35b4007967fd7ba003f2a84b7a53aaf6f6a0e66249c18d2fc4253b5,0866383004,2020-09-11,1
8614937,2019-04-11,3466e024e649971a9cd2c411b34fa5882648cf6a413a966ede30e53d4a69bb65,0708379002,2019-04-12,1
443900,2018-09-29,34003a0756c38058c50e8eeba4cd2c4c7af433257fa13b7d7b3faf933940a2c7,0651222002,2018-10-05,1
13236633,2019-07-03,873496e698e4ebe48d8b10f456c54991de3a5364def03fd6ba4fa18ec16a4fd1,0596119001,2019-07-05,1
6188815,2019-02-14,a7cbbeafe87a225affd26e94f0ce6b9b26ad9ecf101ca10fe40145daab48bf3c,0408647008,2019-02-15,1
27516534,2020-06-18,d7266b793a0f0d88882d68aaea54ffa1860be8168c78e21b7435631a399659e6,0843793001,2020-06-19,1
25318952,2020-05-02,6d8305f2a289ee508088ac1eb83f794a95f5948451ff220974ff8d93fc65ac08,0837941001,2020-05-08,1
30666892,2020-08-24,0a72cba855e3b0d9723fa1742a539fca40567a1992ab1c6cfbef8713664893a9,0803757004,2020-08-28,1
26832947,2020-06-05,1b41b04ebe7b0b8c3b9811e587b55f5fc2e5b383fb33331715dbf6174803b048,0876053002,2020-06-05,1
19409592,2019-11-28,7d9e67165744216311a7fdc07089d26ed916a3d54d47e628c3eb6c8765795b1c,0792817001,2019-11-29,1
9224237,2019-04-24,3bfe7ae91681659b2bef61b5a57fde18c8e201acc1d86cadd2c36c20c0c46008,0568601006,2019-04-26,1
15612944,2019-08-18,06605e19bbc6edf2ac2909ab92273a83f8f20c1e7e84e001f4f53f1a534a7488,0784113001,2019-08-23,1
6371752,2019-02-19,ba68ce1d1637b17d342ac625cdadd9bf683bb6fa0212bc41715b2ab6da39dee5,0701016001,2019-02-22,1
153154,2018-09-23,c078c63358442f65b6c0ceb302274ced4ad5528f91fc74e42390ecd0daf906bc,0397068012,2018-09-28,1
19617693,2019-11-29,f4ead16535c55e2a3eb9dbea5b81da33be8dbc35c889f5122a660e5d4217b2d3,0681373019,2019-11-29,1
16494653,2019-09-11,56a41440affbc7462615d0725e4c4cf8379d95f8ac9ae1d7747e3500d968306f,0762796004,2019-09-13,1
758383,2018-10-05,4104330b2b0b496b5b2fe94ccbb3e627c799e419bd25090db93a843aea492f65,0662257001,2018-10-05,1
26904467,2020-06-06,a5266b6fbdbf55c135c21e5763c07838f213492b53c3b315121b5386ae3b1687,0678942037,2020-06-12,1
30891305,2020-08-29,65bbbae08f1bf21ac33a8c3f44b7d5e648b0cbbea35f620beceb36084e278474,0904545002,2020-09-04,1
2420463,2018-11-13,3e2ade7d50ad66e98186e9db53832848496bd86c14a58fdf96c51be282e4ca3f,0681916004,2018-11-16,1
10472404,2019-05-19,185d647c0155e22187784f8632408b4509e14c5fedebaa6105594dd86f4a3259,0690713010,2019-05-24,1
22744035,2020-02-26,571abc187ce8fd5c8d69faaf8094eed5ec579b3792eb667b3ebd630ebb670430,0823791006,2020-02-28,1
11402024,2019-06-05,7b676bcb1cec4323b3dda45a48cc47c97147c41a213ec96e44fe0c90e4bb5be9,0672625004,2019-06-07,1
22779133,2020-02-27,39a3eea894d4be0b571d66becb6ad9c01dfbc3d7e3aa7ba3776537e3030759c8,0830784001,2020-02-28,1
21824124,2020-01-30,4c70c9ab75cf2f718a21f4a57daf2ad2c0319b144963b95acedf4c7e833db3e9,0685814047,2020-01-31,1
2248261,2018-11-08,39076c14992fba0d95d6d45f22c2c503963ed8836259d83bdc6b5ecda8d6f2e7,0662888005,2018-11-09,1
10294636,2019-05-16,1f8c94995b8102bfb1fd93cd70d90d8d6d41921165dc3922ae4426c0f86b7b76,0681385003,2019-05-17,1
20122676,2019-12-14,5df1005c60151edc650ed79b58e7d8bbcfb6664674baeac540893ad12ef76bae,0826776001,2019-12-20,1
23871524,2020-03-30,3c0fb1daa5139911bc27a5172cf65811cbb0488b0759b21ea9c861c696b86526,0821115002,2020-04-03,1
10104288,2019-05-11,58e57c3f54acfb8cdcae5939222ddc2a3e29c99dc5d8210f6df88266b6e88b9e,0708478001,2019-05-17,1
10587738,2019-05-21,dfe7e6ce3cde96e4545b5cf1f6c5918e6e74cc2c4a8dceb2501d2210c8997a4f,0695545002,2019-05-24,1
20527189,2019-12-23,5260372611b0d7965e9e37e3fb431d6e348488bd8c7b991006eb01b30a49d370,0733045001,2019-12-27,1
25644308,2020-05-12,3817b8e643dd6f66f48631dea054468744a717b07d05921c1b644103a369c901,0736681007,2020-05-15,1
28840394,2020-07-10,33f27d1a92af3c3b0564eb81650568368807875f4e7bc05ddf7510ed57fdaa16,0691855012,2020-07-10,1
26443764,2020-05-28,5443964aedf0673793b38d78f15a4a0dfc3b64d8aa069c744a2facc0495aa784,0610776001,2020-05-29,1
24838105,2020-04-20,130d41de31ab0f530daf2408972a9cbd1f8b80bf8186144345d87f0afd32cb8e,0850893001,2020-04-24,1
14418498,2019-07-24,80cc7e1ed463f077046a675961a027a8ba759b9e4fdb53d74b3d97f292c332b0,0736218001,2019-07-26,1
3307342,2018-12-02,67048950a088bccf6b7ca8fa8b0a12a47962562f54b3a7c08474b332bb462b77,0396135047,2018-12-07,1
25932993,2020-05-19,2f109864d25ec1ebd3f56d7484a3551125bab7a703ab441767273c0405df62e5,0864928001,2020-05-22,1
22855518,2020-02-29,3a5da2c16f1052476a8601a148c74a36aa2dc3733664e66d07e1e289270970a1,0822115004,2020-03-06,1
31628043,2020-09-18,514d5cc00cf2c8719458da2ea3337f4167d5340a682310d7ad50123d45850739,0933032002,2020-09-18,1
30472817,2020-08-18,8d55b4ba692580d48ce270e78f368fd4231a752f1abbbb03daaecc9c62fbee25,0905507003,2020-08-21,1
30578276,2020-08-21,6dd6306381ffcaa7fe3fd08aebd5ed4d3b547175cd67ae27e2480354cae9823f,0610776083,2020-08-21,1
21082098,2020-01-08,d39d101148eeebdf8cc0d3aaa32acd6743eb223e5bc44a2ba14dfa8aadd5fa47,0782874001,2020-01-10,1
222477,2018-09-25,3e95ffa5e686bbb55acaa1f4449340e3cb8d1946d62378e67d807da4daa41679,0189616006,2018-09-28,1
19578381,2019-11-29,b5705c172b861c6cb9a8aa14619bce17ff154341fdb10897279025cafc3da6a4,0787853005,2019-11-29,1
28881520,2020-07-11,278aa2097e20a94d6e505da37e41dcc5abc76b78bc27c87ea62a0e875036b610,0766495014,2020-07-17,1
23899395,2020-03-30,fce2a81c1f48a2f451b9a7812c85f99911221242ec9c82e4f5a3532413b11490,0848988001,2020-04-03,1
1887921,2018-10-29,818d9e35537115612476357ec4d27f4d045da48a1ffb6df2d76db22540f1669f,0695972003,2018-11-02,1
106192,2018-09-22,930c326188de496d96e1b365b7b41b23ec36a69af600ea2ac6c216ab74a832d4,0529953001,2018-09-28,1
559678,2018-09-30,14e81f0d467b3dcea4ad85453bc0d5f998af31c0da811809a06c18f7fd5d4842,0516903011,2018-10-05,1
28518866,2020-07-03,0a2de6c095c0771aa5bc2153c37938a07e7daa2bdcd159c8b534c779cb58a276,0660497006,2020-07-03,1
30217693,2020-08-11,deb45961e00f511bc24036d489e208aabb5363483389148dd42c508699586799,0716672018,2020-08-14,1
26507672,2020-05-29,62f4234f20f3a53aa5460c0b40ae1d7829b85dffd72bacce9fc7c4afb6231929,0711582001,2020-05-29,1
29923719,2020-08-04,d04835e523ad0a813069e0252ddbf8b70d7d841429e5d8b4e2fc90e2035f314a,0791587009,2020-08-07,1
23471347,2020-03-16,e78a7b0b3ef980f30305112c9aa04f6957864609f8fdef344b3abba8ae54d2d6,0812364005,2020-03-20,1
31221725,2020-09-07,154446b891fe22b1d7b7351ff4c06f08fcda2d170cb95498dcaf91612ded159a,0872537001,2020-09-11,1
3425637,2018-12-06,35c069a2b893fe405b86c89895a00665dc74a5eee2b19b881262beae120d76ac,0678073001,2018-12-07,1
1790744,2018-10-27,a3f5ab13bbf88a2ee1c3ae809a5113ee57ceb904a4d9a9d46aa4c69f6256c1ae,0656065001,2018-11-02,1
26259425,2020-05-25,1c843c9a9555a6715acde32dec39757cfc8562dab3009b3da71af35fedabc34a,0771383002,2020-05-29,1
25512638,2020-05-08,9ef729cd563ba2556d3e2585977104616761009a0f5fd3c2270640aac96e3b86,0575347003,2020-05-08,1
18999981,2019-11-16,1f67c9cd04038bed60dc526f03479b380f579bdec4c5ab756496b6d9abe55dbd,0720125017,2019-11-22,1

time: 26.6 ms (started: 2022-05-03 01:30:55 +00:00)

In [ ]:
weekly_sales = weekly_sales.reset_index().set_index('article_id')
last_day = last_ts.strftime('%Y-%m-%d')

time: 5.5 ms (started: 2022-05-03 01:30:58 +00:00)

In [ ]:
last_day

'2020-09-18'

time: 5 ms (started: 2022-05-03 01:44:43 +00:00)

In [ ]:
weekly_sales

                 ldbw  count
article_id
0189616006 2018-09-28  1
0397068012 2018-09-28  1
0529953001 2018-09-28  1
0622295001 2018-09-28  1
0516903011 2018-10-05  1
0651222002 2018-10-05  1
0662257001 2018-10-05  1
0529012011 2018-10-26  1
0656065001 2018-11-02  1
0695972003 2018-11-02  1
0662888005 2018-11-09  1
0665817001 2018-11-09  1
0681916004 2018-11-16  1
0396135047 2018-12-07  1
0678073001 2018-12-07  1
0461327001 2018-12-21  1
0736102002 2019-02-01  1
0408647008 2019-02-15  1
0516000044 2019-02-22  1
0701016001 2019-02-22  1
0680262001 2019-03-01  1
0569986024 2019-03-15  1
0465655016 2019-04-12  1
0708379002 2019-04-12  1
0680262004 2019-04-19  1
0568601006 2019-04-26  1
0701229001 2019-04-26  1
0681385003 2019-05-17  1
0708478001 2019-05-17  1
0690713010 2019-05-24  1
0695545002 2019-05-24  1
0768759005 2019-05-24  1
0752193001 2019-05-31  1
0672625004 2019-06-07  1
0685448004 2019-06-07  1
0541519034 2019-06-14  1
0734236001 2019-06-21  1
0596119001 2019-07-05  1
0692709002 2019-07-05  1
0770212001 2019-07-12  1
0772005005 2019-07-12  1
0736218001 2019-07-26  1
0614854008 2019-08-02  1
0723349001 2019-08-02  1
0784113001 2019-08-23  1
0762796004 2019-09-13  1
0678696014 2019-10-04  1
0720125017 2019-11-22  1
0681373019 2019-11-29  1
0787853005 2019-11-29  1
0792817001 2019-11-29  1
0660726005 2019-12-20  1
0803986011 2019-12-20  1
0826776001 2019-12-20  1
0733045001 2019-12-27  1
0767317001 2019-12-27  1
0789909001 2019-12-27  1
0782874001 2020-01-10  1
0836142001 2020-01-10  1
0856440001 2020-01-10  1
0660308001 2020-01-17  1
0685814047 2020-01-31  1
0739362001 2020-02-28  1
0823791006 2020-02-28  1
0830784001 2020-02-28  1
0822115004 2020-03-06  1
0812364005 2020-03-20  1
0821115002 2020-04-03  1
0848988001 2020-04-03  1
0733097008 2020-04-17  1
0759871004 2020-04-17  1
0850893001 2020-04-24  1
0575347003 2020-05-08  1
0837941001 2020-05-08  1
0736681007 2020-05-15  1
0864928001 2020-05-22  1
0610776001 2020-05-29  1
0711582001 2020-05-29  1
0741220004 2020-05-29  1
0771383002 2020-05-29  1
0806248005 2020-05-29  1
0852614002 2020-06-05  1
0876053002 2020-06-05  1
0678942037 2020-06-12  1
0843793001 2020-06-19  1
0660497006 2020-07-03  1
0691855012 2020-07-10  1
0759871025 2020-07-17  1
0766495014 2020-07-17  1
0609598006 2020-07-31  1
0791587009 2020-08-07  1
0716672018 2020-08-14  1
0554598071 2020-08-21  1
0610776083 2020-08-21  1
0905507003 2020-08-21  1
0803757004 2020-08-28  1
0904545002 2020-09-04  1
0866383004 2020-09-11  1
0872537001 2020-09-11  1
0933032002 2020-09-18  1

time: 19.1 ms (started: 2022-05-03 01:30:59 +00:00)

In [ ]:
df = df.join(
    weekly_sales.loc[weekly_sales['ldbw']==last_day, ['count']],
    on='article_id', rsuffix="_targ")

time: 9.4 ms (started: 2022-05-03 01:31:02 +00:00)

In [ ]:
df

,t_dat,customer_id,article_id,ldbw,count,count_targ
6867893,2019-03-01,f7baf8f7d0435be63c0a94b07ddfa07ab5cc2a5e133e001323a5e2d8eff0cf1c,0680262001,2019-03-01,1,NaN
20191614,2019-12-16,a5230cd414c9718e1735cacc4357096914f9f36fefba8a24b94aa9f1d5699997,0803986011,2019-12-20,1,NaN
6294079,2019-02-17,5daca4a44cd1e355dce96a6ae0a6e483a3c92c16f89d37ebaf0e2f83671aa982,0516000044,2019-02-22,1,NaN
2162782,2018-11-05,b379a3233c1395197c54e6ca11674b3e23a856531e01b5bf657f64ac9b93630d,0665817001,2018-11-09,1,NaN
21032772,2020-01-07,678a749aacb1a5b3faedaf5bc8bc23720cbf618d2ab8d32b9536d9203e1b27e6,0856440001,2020-01-10,1,NaN
21184942,2020-01-11,adb59c69cc7e2841741c5e529292c628e1ac19d8b5ca0e078322ad335d4f70c5,0660308001,2020-01-17,1,NaN
14860519,2019-07-31,eec7eca2db06856e95638836eecdf4860563bc4e1b20311e604b90c597badc13,0723349001,2019-08-02,1,NaN
17234441,2019-09-28,cdcb5ae7187a23a874511becfb9dba028a1fc6ffe85c5e3bde42631574c74902,0678696014,2019-10-04,1,NaN
24523061,2020-04-11,a7fbc1eb6472d798b95b3b742c7abb20c73a1b5b4e79a7ebfadb6b4d814cdf63,0759871004,2020-04-17,1,NaN
21039707,2020-01-07,a41776ed1a169af3ead7c64932f3f9e7f8042c010f4668292d28ff5ba46bd01b,0836142001,2020-01-10,1,NaN
3820590,2018-12-17,c2f0cdda2dc3042ccd9fcd8253fd8e368769840581e40aab1d87a64ff39987e3,0461327001,2018-12-21,1,NaN
29065452,2020-07-15,c7e366346a0e8284ae4a7a7c49618d9240077b2bd507837ea7b732f73e394908,0759871025,2020-07-17,1,NaN
12129018,2019-06-19,cf7a1056a22451a0eb6f7dd61b925f4a886a4150e99b52b007a18d8318dfbd25,0734236001,2019-06-21,1,NaN
9176547,2019-04-23,885ebfa1515a85ba9feb47fa407f10c4c9611235b059fbdacfdb09042a79d7c2,0701229001,2019-04-26,1,NaN
26336527,2020-05-26,8f4d9b1db310c83fd04e5540e9eac7e90e999ec011f0caae30957069519db782,0741220004,2020-05-29,1,NaN
11353636,2019-06-04,91c6f4f37786556425cc8aea814a20f1a00e2fe9890d8e40b36ef4a9dcf87373,0685448004,2019-06-07,1,NaN
26315640,2020-05-26,2f1055deed1fc1d2ea8da13666faeb93f6e9c8f6597e0bc8c552efab213218de,0806248005,2020-05-29,1,NaN
13694456,2019-07-11,a9dae6f31cd2feafc0eebe48ba236cc7fadc62287d7e7636c7699259bb3eeef4,0770212001,2019-07-12,1,NaN
5597463,2019-01-30,00e1fc813958a3b6b932b1eecba91895bbbeb722752c8486bee500a912125143,0736102002,2019-02-01,1,NaN
13388550,2019-07-06,0e90161bc18662657b18dd5ed863cf5e8be27c6c6da1adabff7fbe504447eb62,0772005005,2019-07-12,1,NaN
10993310,2019-05-29,6be4f587cdb5997111cc4401e475bb836ce2496d16617a5b1f48d97a80c62498,0752193001,2019-05-31,1,NaN
22741224,2020-02-26,445571567813c79aedc3179baa023da67cc87452cd7031cf023f28767e0c2932,0739362001,2020-02-28,1,NaN
8414799,2019-04-06,b90a8270c6f10402cca365cddf1e1e9138a07ac19b2fd6b07dfeb921b91976ce,0465655016,2019-04-12,1,NaN
24567714,2020-04-11,ed6dbc458d114a5dfbd1f97e33195032b4f2d2a89dd5c81f2fea2bf78b3e7216,0733097008,2020-04-17,1,NaN
7161402,2019-03-09,6e0f8a1cb0777d7e6f10688dd0f1e6019f1281f6a54d4b30175870edc530055f,0569986024,2019-03-15,1,NaN
20255535,2019-12-18,4d55bba6821c65d765df96fad06504e51e1aada172d70d43c14c0f31ed368194,0660726005,2019-12-20,1,NaN
20584658,2019-12-24,99bf05e9c6f163dbb10c9d7d5c371b189dfcc33799e43f2622b03a6a13b63c90,0767317001,2019-12-27,1,NaN
111794,2018-09-22,e3fa3038af5d048ba927e93ee544b6a0fe7a14c83bfa645d7d3c3d3afef4c6e2,0622295001,2018-09-28,1,NaN
8817704,2019-04-15,f7f39b58a1e54a8539d970280c1d177e0dde7a5840af984425e7baf8daa58618,0680262004,2019-04-19,1,NaN
14698324,2019-07-28,e23d51b58780cc241dd4a412f72f82e0876ce41aabd97ae32622484eb6fa61ad,0614854008,2019-08-02,1,NaN
26584583,2020-05-30,a7b299f3f2b14efed1ff4a1dd49127627c8649183cb4635f5dee6837c36c89b0,0852614002,2020-06-05,1,NaN
29578532,2020-07-28,3b4cffd4376393398d6eeafdd70bfad80d5da6bd092b7b0d9ffb5e59b5a87235,0609598006,2020-07-31,1,NaN
20578294,2019-12-24,6e7938c489f593b748740b62482b66cefa9cffe29739d87d48f68e8e78728eb5,0789909001,2019-12-27,1,NaN
10563939,2019-05-21,53297251042630e4725ae591a97c3b4ab40f790fd47fe1d382b49ba4867b166f,0768759005,2019-05-24,1,NaN
13010197,2019-06-30,35bdc9d61d688a7d5ea59011ccfe0b2ad3a2ffc77d9e007e642e94311e77bfd5,0692709002,2019-07-05,1,NaN
11603205,2019-06-09,e43d0f5e178aadbe2346eed4e6969f8352fea3851b13e941e9a17be328559ab8,0541519034,2019-06-14,1,NaN
30413708,2020-08-16,aca3fecf77c200bb6bfc69e0a5e77cfc3712d621793eee12b2ad6464853a603b,0554598071,2020-08-21,1,NaN
1541252,2018-10-23,2619f506d7b3d126e93212246955550735a370d8fe0bec90c4123540186a88a5,0529012011,2018-10-26,1,NaN
31400948,2020-09-11,b409676fb35b4007967fd7ba003f2a84b7a53aaf6f6a0e66249c18d2fc4253b5,0866383004,2020-09-11,1,NaN
8614937,2019-04-11,3466e024e649971a9cd2c411b34fa5882648cf6a413a966ede30e53d4a69bb65,0708379002,2019-04-12,1,NaN
443900,2018-09-29,34003a0756c38058c50e8eeba4cd2c4c7af433257fa13b7d7b3faf933940a2c7,0651222002,2018-10-05,1,NaN
13236633,2019-07-03,873496e698e4ebe48d8b10f456c54991de3a5364def03fd6ba4fa18ec16a4fd1,0596119001,2019-07-05,1,NaN
6188815,2019-02-14,a7cbbeafe87a225affd26e94f0ce6b9b26ad9ecf101ca10fe40145daab48bf3c,0408647008,2019-02-15,1,NaN
27516534,2020-06-18,d7266b793a0f0d88882d68aaea54ffa1860be8168c78e21b7435631a399659e6,0843793001,2020-06-19,1,NaN
25318952,2020-05-02,6d8305f2a289ee508088ac1eb83f794a95f5948451ff220974ff8d93fc65ac08,0837941001,2020-05-08,1,NaN
30666892,2020-08-24,0a72cba855e3b0d9723fa1742a539fca40567a1992ab1c6cfbef8713664893a9,0803757004,2020-08-28,1,NaN
26832947,2020-06-05,1b41b04ebe7b0b8c3b9811e587b55f5fc2e5b383fb33331715dbf6174803b048,0876053002,2020-06-05,1,NaN
19409592,2019-11-28,7d9e67165744216311a7fdc07089d26ed916a3d54d47e628c3eb6c8765795b1c,0792817001,2019-11-29,1,NaN
9224237,2019-04-24,3bfe7ae91681659b2bef61b5a57fde18c8e201acc1d86cadd2c36c20c0c46008,0568601006,2019-04-26,1,NaN
15612944,2019-08-18,06605e19bbc6edf2ac2909ab92273a83f8f20c1e7e84e001f4f53f1a534a7488,0784113001,2019-08-23,1,NaN
6371752,2019-02-19,ba68ce1d1637b17d342ac625cdadd9bf683bb6fa0212bc41715b2ab6da39dee5,0701016001,2019-02-22,1,NaN
153154,2018-09-23,c078c63358442f65b6c0ceb302274ced4ad5528f91fc74e42390ecd0daf906bc,0397068012,2018-09-28,1,NaN
19617693,2019-11-29,f4ead16535c55e2a3eb9dbea5b81da33be8dbc35c889f5122a660e5d4217b2d3,0681373019,2019-11-29,1,NaN
16494653,2019-09-11,56a41440affbc7462615d0725e4c4cf8379d95f8ac9ae1d7747e3500d968306f,0762796004,2019-09-13,1,NaN
758383,2018-10-05,4104330b2b0b496b5b2fe94ccbb3e627c799e419bd25090db93a843aea492f65,0662257001,2018-10-05,1,NaN
26904467,2020-06-06,a5266b6fbdbf55c135c21e5763c07838f213492b53c3b315121b5386ae3b1687,0678942037,2020-06-12,1,NaN
30891305,2020-08-29,65bbbae08f1bf21ac33a8c3f44b7d5e648b0cbbea35f620beceb36084e278474,0904545002,2020-09-04,1,NaN
2420463,2018-11-13,3e2ade7d50ad66e98186e9db53832848496bd86c14a58fdf96c51be282e4ca3f,0681916004,2018-11-16,1,NaN
10472404,2019-05-19,185d647c0155e22187784f8632408b4509e14c5fedebaa6105594dd86f4a3259,0690713010,2019-05-24,1,NaN
22744035,2020-02-26,571abc187ce8fd5c8d69faaf8094eed5ec579b3792eb667b3ebd630ebb670430,0823791006,2020-02-28,1,NaN
11402024,2019-06-05,7b676bcb1cec4323b3dda45a48cc47c97147c41a213ec96e44fe0c90e4bb5be9,0672625004,2019-06-07,1,NaN
22779133,2020-02-27,39a3eea894d4be0b571d66becb6ad9c01dfbc3d7e3aa7ba3776537e3030759c8,0830784001,2020-02-28,1,NaN
21824124,2020-01-30,4c70c9ab75cf2f718a21f4a57daf2ad2c0319b144963b95acedf4c7e833db3e9,0685814047,2020-01-31,1,NaN
2248261,2018-11-08,39076c14992fba0d95d6d45f22c2c503963ed8836259d83bdc6b5ecda8d6f2e7,0662888005,2018-11-09,1,NaN
10294636,2019-05-16,1f8c94995b8102bfb1fd93cd70d90d8d6d41921165dc3922ae4426c0f86b7b76,0681385003,2019-05-17,1,NaN
20122676,2019-12-14,5df1005c60151edc650ed79b58e7d8bbcfb6664674baeac540893ad12ef76bae,0826776001,2019-12-20,1,NaN
23871524,2020-03-30,3c0fb1daa5139911bc27a5172cf65811cbb0488b0759b21ea9c861c696b86526,0821115002,2020-04-03,1,NaN
10104288,2019-05-11,58e57c3f54acfb8cdcae5939222ddc2a3e29c99dc5d8210f6df88266b6e88b9e,0708478001,2019-05-17,1,NaN
10587738,2019-05-21,dfe7e6ce3cde96e4545b5cf1f6c5918e6e74cc2c4a8dceb2501d2210c8997a4f,0695545002,2019-05-24,1,NaN
20527189,2019-12-23,5260372611b0d7965e9e37e3fb431d6e348488bd8c7b991006eb01b30a49d370,0733045001,2019-12-27,1,NaN
25644308,2020-05-12,3817b8e643dd6f66f48631dea054468744a717b07d05921c1b644103a369c901,0736681007,2020-05-15,1,NaN
28840394,2020-07-10,33f27d1a92af3c3b0564eb81650568368807875f4e7bc05ddf7510ed57fdaa16,0691855012,2020-07-10,1,NaN
26443764,2020-05-28,5443964aedf0673793b38d78f15a4a0dfc3b64d8aa069c744a2facc0495aa784,0610776001,2020-05-29,1,NaN
24838105,2020-04-20,130d41de31ab0f530daf2408972a9cbd1f8b80bf8186144345d87f0afd32cb8e,0850893001,2020-04-24,1,NaN
14418498,2019-07-24,80cc7e1ed463f077046a675961a027a8ba759b9e4fdb53d74b3d97f292c332b0,0736218001,2019-07-26,1,NaN
3307342,2018-12-02,67048950a088bccf6b7ca8fa8b0a12a47962562f54b3a7c08474b332bb462b77,0396135047,2018-12-07,1,NaN
25932993,2020-05-19,2f109864d25ec1ebd3f56d7484a3551125bab7a703ab441767273c0405df62e5,0864928001,2020-05-22,1,NaN
22855518,2020-02-29,3a5da2c16f1052476a8601a148c74a36aa2dc3733664e66d07e1e289270970a1,0822115004,2020-03-06,1,NaN
31628043,2020-09-18,514d5cc00cf2c8719458da2ea3337f4167d5340a682310d7ad50123d45850739,0933032002,2020-09-18,1,1.0
30472817,2020-08-18,8d55b4ba692580d48ce270e78f368fd4231a752f1abbbb03daaecc9c62fbee25,0905507003,2020-08-21,1,NaN
30578276,2020-08-21,6dd6306381ffcaa7fe3fd08aebd5ed4d3b547175cd67ae27e2480354cae9823f,0610776083,2020-08-21,1,NaN
21082098,2020-01-08,d39d101148eeebdf8cc0d3aaa32acd6743eb223e5bc44a2ba14dfa8aadd5fa47,0782874001,2020-01-10,1,NaN
222477,2018-09-25,3e95ffa5e686bbb55acaa1f4449340e3cb8d1946d62378e67d807da4daa41679,0189616006,2018-09-28,1,NaN
19578381,2019-11-29,b5705c172b861c6cb9a8aa14619bce17ff154341fdb10897279025cafc3da6a4,0787853005,2019-11-29,1,NaN
28881520,2020-07-11,278aa2097e20a94d6e505da37e41dcc5abc76b78bc27c87ea62a0e875036b610,0766495014,2020-07-17,1,NaN
23899395,2020-03-30,fce2a81c1f48a2f451b9a7812c85f99911221242ec9c82e4f5a3532413b11490,0848988001,2020-04-03,1,NaN
1887921,2018-10-29,818d9e35537115612476357ec4d27f4d045da48a1ffb6df2d76db22540f1669f,0695972003,2018-11-02,1,NaN
106192,2018-09-22,930c326188de496d96e1b365b7b41b23ec36a69af600ea2ac6c216ab74a832d4,0529953001,2018-09-28,1,NaN
559678,2018-09-30,14e81f0d467b3dcea4ad85453bc0d5f998af31c0da811809a06c18f7fd5d4842,0516903011,2018-10-05,1,NaN
28518866,2020-07-03,0a2de6c095c0771aa5bc2153c37938a07e7daa2bdcd159c8b534c779cb58a276,0660497006,2020-07-03,1,NaN
30217693,2020-08-11,deb45961e00f511bc24036d489e208aabb5363483389148dd42c508699586799,0716672018,2020-08-14,1,NaN
26507672,2020-05-29,62f4234f20f3a53aa5460c0b40ae1d7829b85dffd72bacce9fc7c4afb6231929,0711582001,2020-05-29,1,NaN
29923719,2020-08-04,d04835e523ad0a813069e0252ddbf8b70d7d841429e5d8b4e2fc90e2035f314a,0791587009,2020-08-07,1,NaN
23471347,2020-03-16,e78a7b0b3ef980f30305112c9aa04f6957864609f8fdef344b3abba8ae54d2d6,0812364005,2020-03-20,1,NaN
31221725,2020-09-07,154446b891fe22b1d7b7351ff4c06f08fcda2d170cb95498dcaf91612ded159a,0872537001,2020-09-11,1,NaN
3425637,2018-12-06,35c069a2b893fe405b86c89895a00665dc74a5eee2b19b881262beae120d76ac,0678073001,2018-12-07,1,NaN
1790744,2018-10-27,a3f5ab13bbf88a2ee1c3ae809a5113ee57ceb904a4d9a9d46aa4c69f6256c1ae,0656065001,2018-11-02,1,NaN
26259425,2020-05-25,1c843c9a9555a6715acde32dec39757cfc8562dab3009b3da71af35fedabc34a,0771383002,2020-05-29,1,NaN
25512638,2020-05-08,9ef729cd563ba2556d3e2585977104616761009a0f5fd3c2270640aac96e3b86,0575347003,2020-05-08,1,NaN
18999981,2019-11-16,1f67c9cd04038bed60dc526f03479b380f579bdec4c5ab756496b6d9abe55dbd,0720125017,2019-11-22,1,NaN

time: 30.3 ms (started: 2022-05-03 01:31:04 +00:00)

In [ ]:
df['count_targ'].fillna(0, inplace=True)
del weekly_sales
df['quotient'] = df['count_targ'] / df['count']

time: 10.7 ms (started: 2022-05-03 01:31:06 +00:00)

In [ ]:
df

,t_dat,customer_id,article_id,ldbw,count,count_targ,quotient
6867893,2019-03-01,f7baf8f7d0435be63c0a94b07ddfa07ab5cc2a5e133e001323a5e2d8eff0cf1c,0680262001,2019-03-01,1,0.0,0.0
20191614,2019-12-16,a5230cd414c9718e1735cacc4357096914f9f36fefba8a24b94aa9f1d5699997,0803986011,2019-12-20,1,0.0,0.0
6294079,2019-02-17,5daca4a44cd1e355dce96a6ae0a6e483a3c92c16f89d37ebaf0e2f83671aa982,0516000044,2019-02-22,1,0.0,0.0
2162782,2018-11-05,b379a3233c1395197c54e6ca11674b3e23a856531e01b5bf657f64ac9b93630d,0665817001,2018-11-09,1,0.0,0.0
21032772,2020-01-07,678a749aacb1a5b3faedaf5bc8bc23720cbf618d2ab8d32b9536d9203e1b27e6,0856440001,2020-01-10,1,0.0,0.0
21184942,2020-01-11,adb59c69cc7e2841741c5e529292c628e1ac19d8b5ca0e078322ad335d4f70c5,0660308001,2020-01-17,1,0.0,0.0
14860519,2019-07-31,eec7eca2db06856e95638836eecdf4860563bc4e1b20311e604b90c597badc13,0723349001,2019-08-02,1,0.0,0.0
17234441,2019-09-28,cdcb5ae7187a23a874511becfb9dba028a1fc6ffe85c5e3bde42631574c74902,0678696014,2019-10-04,1,0.0,0.0
24523061,2020-04-11,a7fbc1eb6472d798b95b3b742c7abb20c73a1b5b4e79a7ebfadb6b4d814cdf63,0759871004,2020-04-17,1,0.0,0.0
21039707,2020-01-07,a41776ed1a169af3ead7c64932f3f9e7f8042c010f4668292d28ff5ba46bd01b,0836142001,2020-01-10,1,0.0,0.0
3820590,2018-12-17,c2f0cdda2dc3042ccd9fcd8253fd8e368769840581e40aab1d87a64ff39987e3,0461327001,2018-12-21,1,0.0,0.0
29065452,2020-07-15,c7e366346a0e8284ae4a7a7c49618d9240077b2bd507837ea7b732f73e394908,0759871025,2020-07-17,1,0.0,0.0
12129018,2019-06-19,cf7a1056a22451a0eb6f7dd61b925f4a886a4150e99b52b007a18d8318dfbd25,0734236001,2019-06-21,1,0.0,0.0
9176547,2019-04-23,885ebfa1515a85ba9feb47fa407f10c4c9611235b059fbdacfdb09042a79d7c2,0701229001,2019-04-26,1,0.0,0.0
26336527,2020-05-26,8f4d9b1db310c83fd04e5540e9eac7e90e999ec011f0caae30957069519db782,0741220004,2020-05-29,1,0.0,0.0
11353636,2019-06-04,91c6f4f37786556425cc8aea814a20f1a00e2fe9890d8e40b36ef4a9dcf87373,0685448004,2019-06-07,1,0.0,0.0
26315640,2020-05-26,2f1055deed1fc1d2ea8da13666faeb93f6e9c8f6597e0bc8c552efab213218de,0806248005,2020-05-29,1,0.0,0.0
13694456,2019-07-11,a9dae6f31cd2feafc0eebe48ba236cc7fadc62287d7e7636c7699259bb3eeef4,0770212001,2019-07-12,1,0.0,0.0
5597463,2019-01-30,00e1fc813958a3b6b932b1eecba91895bbbeb722752c8486bee500a912125143,0736102002,2019-02-01,1,0.0,0.0
13388550,2019-07-06,0e90161bc18662657b18dd5ed863cf5e8be27c6c6da1adabff7fbe504447eb62,0772005005,2019-07-12,1,0.0,0.0
10993310,2019-05-29,6be4f587cdb5997111cc4401e475bb836ce2496d16617a5b1f48d97a80c62498,0752193001,2019-05-31,1,0.0,0.0
22741224,2020-02-26,445571567813c79aedc3179baa023da67cc87452cd7031cf023f28767e0c2932,0739362001,2020-02-28,1,0.0,0.0
8414799,2019-04-06,b90a8270c6f10402cca365cddf1e1e9138a07ac19b2fd6b07dfeb921b91976ce,0465655016,2019-04-12,1,0.0,0.0
24567714,2020-04-11,ed6dbc458d114a5dfbd1f97e33195032b4f2d2a89dd5c81f2fea2bf78b3e7216,0733097008,2020-04-17,1,0.0,0.0
7161402,2019-03-09,6e0f8a1cb0777d7e6f10688dd0f1e6019f1281f6a54d4b30175870edc530055f,0569986024,2019-03-15,1,0.0,0.0
20255535,2019-12-18,4d55bba6821c65d765df96fad06504e51e1aada172d70d43c14c0f31ed368194,0660726005,2019-12-20,1,0.0,0.0
20584658,2019-12-24,99bf05e9c6f163dbb10c9d7d5c371b189dfcc33799e43f2622b03a6a13b63c90,0767317001,2019-12-27,1,0.0,0.0
111794,2018-09-22,e3fa3038af5d048ba927e93ee544b6a0fe7a14c83bfa645d7d3c3d3afef4c6e2,0622295001,2018-09-28,1,0.0,0.0
8817704,2019-04-15,f7f39b58a1e54a8539d970280c1d177e0dde7a5840af984425e7baf8daa58618,0680262004,2019-04-19,1,0.0,0.0
14698324,2019-07-28,e23d51b58780cc241dd4a412f72f82e0876ce41aabd97ae32622484eb6fa61ad,0614854008,2019-08-02,1,0.0,0.0
26584583,2020-05-30,a7b299f3f2b14efed1ff4a1dd49127627c8649183cb4635f5dee6837c36c89b0,0852614002,2020-06-05,1,0.0,0.0
29578532,2020-07-28,3b4cffd4376393398d6eeafdd70bfad80d5da6bd092b7b0d9ffb5e59b5a87235,0609598006,2020-07-31,1,0.0,0.0
20578294,2019-12-24,6e7938c489f593b748740b62482b66cefa9cffe29739d87d48f68e8e78728eb5,0789909001,2019-12-27,1,0.0,0.0
10563939,2019-05-21,53297251042630e4725ae591a97c3b4ab40f790fd47fe1d382b49ba4867b166f,0768759005,2019-05-24,1,0.0,0.0
13010197,2019-06-30,35bdc9d61d688a7d5ea59011ccfe0b2ad3a2ffc77d9e007e642e94311e77bfd5,0692709002,2019-07-05,1,0.0,0.0
11603205,2019-06-09,e43d0f5e178aadbe2346eed4e6969f8352fea3851b13e941e9a17be328559ab8,0541519034,2019-06-14,1,0.0,0.0
30413708,2020-08-16,aca3fecf77c200bb6bfc69e0a5e77cfc3712d621793eee12b2ad6464853a603b,0554598071,2020-08-21,1,0.0,0.0
1541252,2018-10-23,2619f506d7b3d126e93212246955550735a370d8fe0bec90c4123540186a88a5,0529012011,2018-10-26,1,0.0,0.0
31400948,2020-09-11,b409676fb35b4007967fd7ba003f2a84b7a53aaf6f6a0e66249c18d2fc4253b5,0866383004,2020-09-11,1,0.0,0.0
8614937,2019-04-11,3466e024e649971a9cd2c411b34fa5882648cf6a413a966ede30e53d4a69bb65,0708379002,2019-04-12,1,0.0,0.0
443900,2018-09-29,34003a0756c38058c50e8eeba4cd2c4c7af433257fa13b7d7b3faf933940a2c7,0651222002,2018-10-05,1,0.0,0.0
13236633,2019-07-03,873496e698e4ebe48d8b10f456c54991de3a5364def03fd6ba4fa18ec16a4fd1,0596119001,2019-07-05,1,0.0,0.0
6188815,2019-02-14,a7cbbeafe87a225affd26e94f0ce6b9b26ad9ecf101ca10fe40145daab48bf3c,0408647008,2019-02-15,1,0.0,0.0
27516534,2020-06-18,d7266b793a0f0d88882d68aaea54ffa1860be8168c78e21b7435631a399659e6,0843793001,2020-06-19,1,0.0,0.0
25318952,2020-05-02,6d8305f2a289ee508088ac1eb83f794a95f5948451ff220974ff8d93fc65ac08,0837941001,2020-05-08,1,0.0,0.0
30666892,2020-08-24,0a72cba855e3b0d9723fa1742a539fca40567a1992ab1c6cfbef8713664893a9,0803757004,2020-08-28,1,0.0,0.0
26832947,2020-06-05,1b41b04ebe7b0b8c3b9811e587b55f5fc2e5b383fb33331715dbf6174803b048,0876053002,2020-06-05,1,0.0,0.0
19409592,2019-11-28,7d9e67165744216311a7fdc07089d26ed916a3d54d47e628c3eb6c8765795b1c,0792817001,2019-11-29,1,0.0,0.0
9224237,2019-04-24,3bfe7ae91681659b2bef61b5a57fde18c8e201acc1d86cadd2c36c20c0c46008,0568601006,2019-04-26,1,0.0,0.0
15612944,2019-08-18,06605e19bbc6edf2ac2909ab92273a83f8f20c1e7e84e001f4f53f1a534a7488,0784113001,2019-08-23,1,0.0,0.0
6371752,2019-02-19,ba68ce1d1637b17d342ac625cdadd9bf683bb6fa0212bc41715b2ab6da39dee5,0701016001,2019-02-22,1,0.0,0.0
153154,2018-09-23,c078c63358442f65b6c0ceb302274ced4ad5528f91fc74e42390ecd0daf906bc,0397068012,2018-09-28,1,0.0,0.0
19617693,2019-11-29,f4ead16535c55e2a3eb9dbea5b81da33be8dbc35c889f5122a660e5d4217b2d3,0681373019,2019-11-29,1,0.0,0.0
16494653,2019-09-11,56a41440affbc7462615d0725e4c4cf8379d95f8ac9ae1d7747e3500d968306f,0762796004,2019-09-13,1,0.0,0.0
758383,2018-10-05,4104330b2b0b496b5b2fe94ccbb3e627c799e419bd25090db93a843aea492f65,0662257001,2018-10-05,1,0.0,0.0
26904467,2020-06-06,a5266b6fbdbf55c135c21e5763c07838f213492b53c3b315121b5386ae3b1687,0678942037,2020-06-12,1,0.0,0.0
30891305,2020-08-29,65bbbae08f1bf21ac33a8c3f44b7d5e648b0cbbea35f620beceb36084e278474,0904545002,2020-09-04,1,0.0,0.0
2420463,2018-11-13,3e2ade7d50ad66e98186e9db53832848496bd86c14a58fdf96c51be282e4ca3f,0681916004,2018-11-16,1,0.0,0.0
10472404,2019-05-19,185d647c0155e22187784f8632408b4509e14c5fedebaa6105594dd86f4a3259,0690713010,2019-05-24,1,0.0,0.0
22744035,2020-02-26,571abc187ce8fd5c8d69faaf8094eed5ec579b3792eb667b3ebd630ebb670430,0823791006,2020-02-28,1,0.0,0.0
11402024,2019-06-05,7b676bcb1cec4323b3dda45a48cc47c97147c41a213ec96e44fe0c90e4bb5be9,0672625004,2019-06-07,1,0.0,0.0
22779133,2020-02-27,39a3eea894d4be0b571d66becb6ad9c01dfbc3d7e3aa7ba3776537e3030759c8,0830784001,2020-02-28,1,0.0,0.0
21824124,2020-01-30,4c70c9ab75cf2f718a21f4a57daf2ad2c0319b144963b95acedf4c7e833db3e9,0685814047,2020-01-31,1,0.0,0.0
2248261,2018-11-08,39076c14992fba0d95d6d45f22c2c503963ed8836259d83bdc6b5ecda8d6f2e7,0662888005,2018-11-09,1,0.0,0.0
10294636,2019-05-16,1f8c94995b8102bfb1fd93cd70d90d8d6d41921165dc3922ae4426c0f86b7b76,0681385003,2019-05-17,1,0.0,0.0
20122676,2019-12-14,5df1005c60151edc650ed79b58e7d8bbcfb6664674baeac540893ad12ef76bae,0826776001,2019-12-20,1,0.0,0.0
23871524,2020-03-30,3c0fb1daa5139911bc27a5172cf65811cbb0488b0759b21ea9c861c696b86526,0821115002,2020-04-03,1,0.0,0.0
10104288,2019-05-11,58e57c3f54acfb8cdcae5939222ddc2a3e29c99dc5d8210f6df88266b6e88b9e,0708478001,2019-05-17,1,0.0,0.0
10587738,2019-05-21,dfe7e6ce3cde96e4545b5cf1f6c5918e6e74cc2c4a8dceb2501d2210c8997a4f,0695545002,2019-05-24,1,0.0,0.0
20527189,2019-12-23,5260372611b0d7965e9e37e3fb431d6e348488bd8c7b991006eb01b30a49d370,0733045001,2019-12-27,1,0.0,0.0
25644308,2020-05-12,3817b8e643dd6f66f48631dea054468744a717b07d05921c1b644103a369c901,0736681007,2020-05-15,1,0.0,0.0
28840394,2020-07-10,33f27d1a92af3c3b0564eb81650568368807875f4e7bc05ddf7510ed57fdaa16,0691855012,2020-07-10,1,0.0,0.0
26443764,2020-05-28,5443964aedf0673793b38d78f15a4a0dfc3b64d8aa069c744a2facc0495aa784,0610776001,2020-05-29,1,0.0,0.0
24838105,2020-04-20,130d41de31ab0f530daf2408972a9cbd1f8b80bf8186144345d87f0afd32cb8e,0850893001,2020-04-24,1,0.0,0.0
14418498,2019-07-24,80cc7e1ed463f077046a675961a027a8ba759b9e4fdb53d74b3d97f292c332b0,0736218001,2019-07-26,1,0.0,0.0
3307342,2018-12-02,67048950a088bccf6b7ca8fa8b0a12a47962562f54b3a7c08474b332bb462b77,0396135047,2018-12-07,1,0.0,0.0
25932993,2020-05-19,2f109864d25ec1ebd3f56d7484a3551125bab7a703ab441767273c0405df62e5,0864928001,2020-05-22,1,0.0,0.0
22855518,2020-02-29,3a5da2c16f1052476a8601a148c74a36aa2dc3733664e66d07e1e289270970a1,0822115004,2020-03-06,1,0.0,0.0
31628043,2020-09-18,514d5cc00cf2c8719458da2ea3337f4167d5340a682310d7ad50123d45850739,0933032002,2020-09-18,1,1.0,1.0
30472817,2020-08-18,8d55b4ba692580d48ce270e78f368fd4231a752f1abbbb03daaecc9c62fbee25,0905507003,2020-08-21,1,0.0,0.0
30578276,2020-08-21,6dd6306381ffcaa7fe3fd08aebd5ed4d3b547175cd67ae27e2480354cae9823f,0610776083,2020-08-21,1,0.0,0.0
21082098,2020-01-08,d39d101148eeebdf8cc0d3aaa32acd6743eb223e5bc44a2ba14dfa8aadd5fa47,0782874001,2020-01-10,1,0.0,0.0
222477,2018-09-25,3e95ffa5e686bbb55acaa1f4449340e3cb8d1946d62378e67d807da4daa41679,0189616006,2018-09-28,1,0.0,0.0
19578381,2019-11-29,b5705c172b861c6cb9a8aa14619bce17ff154341fdb10897279025cafc3da6a4,0787853005,2019-11-29,1,0.0,0.0
28881520,2020-07-11,278aa2097e20a94d6e505da37e41dcc5abc76b78bc27c87ea62a0e875036b610,0766495014,2020-07-17,1,0.0,0.0
23899395,2020-03-30,fce2a81c1f48a2f451b9a7812c85f99911221242ec9c82e4f5a3532413b11490,0848988001,2020-04-03,1,0.0,0.0
1887921,2018-10-29,818d9e35537115612476357ec4d27f4d045da48a1ffb6df2d76db22540f1669f,0695972003,2018-11-02,1,0.0,0.0
106192,2018-09-22,930c326188de496d96e1b365b7b41b23ec36a69af600ea2ac6c216ab74a832d4,0529953001,2018-09-28,1,0.0,0.0
559678,2018-09-30,14e81f0d467b3dcea4ad85453bc0d5f998af31c0da811809a06c18f7fd5d4842,0516903011,2018-10-05,1,0.0,0.0
28518866,2020-07-03,0a2de6c095c0771aa5bc2153c37938a07e7daa2bdcd159c8b534c779cb58a276,0660497006,2020-07-03,1,0.0,0.0
30217693,2020-08-11,deb45961e00f511bc24036d489e208aabb5363483389148dd42c508699586799,0716672018,2020-08-14,1,0.0,0.0
26507672,2020-05-29,62f4234f20f3a53aa5460c0b40ae1d7829b85dffd72bacce9fc7c4afb6231929,0711582001,2020-05-29,1,0.0,0.0
29923719,2020-08-04,d04835e523ad0a813069e0252ddbf8b70d7d841429e5d8b4e2fc90e2035f314a,0791587009,2020-08-07,1,0.0,0.0
23471347,2020-03-16,e78a7b0b3ef980f30305112c9aa04f6957864609f8fdef344b3abba8ae54d2d6,0812364005,2020-03-20,1,0.0,0.0
31221725,2020-09-07,154446b891fe22b1d7b7351ff4c06f08fcda2d170cb95498dcaf91612ded159a,0872537001,2020-09-11,1,0.0,0.0
3425637,2018-12-06,35c069a2b893fe405b86c89895a00665dc74a5eee2b19b881262beae120d76ac,0678073001,2018-12-07,1,0.0,0.0
1790744,2018-10-27,a3f5ab13bbf88a2ee1c3ae809a5113ee57ceb904a4d9a9d46aa4c69f6256c1ae,0656065001,2018-11-02,1,0.0,0.0
26259425,2020-05-25,1c843c9a9555a6715acde32dec39757cfc8562dab3009b3da71af35fedabc34a,0771383002,2020-05-29,1,0.0,0.0
25512638,2020-05-08,9ef729cd563ba2556d3e2585977104616761009a0f5fd3c2270640aac96e3b86,0575347003,2020-05-08,1,0.0,0.0
18999981,2019-11-16,1f67c9cd04038bed60dc526f03479b380f579bdec4c5ab756496b6d9abe55dbd,0720125017,2019-11-22,1,0.0,0.0

time: 120 ms (started: 2022-05-03 01:31:11 +00:00)

In [ ]:
purchase_dict = {}
#~35 mins for the loop
for i in tqdm(df.index):
    cust_id = df.at[i, 'customer_id']
    art_id = df.at[i, 'article_id']
    t_dat = df.at[i, 't_dat']

    if cust_id not in purchase_dict:
        purchase_dict[cust_id] = {}

    if art_id not in purchase_dict[cust_id]:
        purchase_dict[cust_id][art_id] = 0
    
    x = max(1, (last_ts - t_dat).days)

    a, b, c, d = 2.5e4, 1.5e5, 2e-1, 1e3
    y = a / np.sqrt(x) + b * np.exp(-c*x) - d

    value = df.at[i, 'quotient'] * max(0, y)
    purchase_dict[cust_id][art_id] += value

100%|ââââââââââ| 100/100 [00:00<00:00, 8102.59it/s]

time: 31.2 ms (started: 2022-05-03 01:31:25 +00:00)

In [ ]:
purchase_dict

{'00e1fc813958a3b6b932b1eecba91895bbbeb722752c8486bee500a912125143': {'0736102002': 0.0},
 '06605e19bbc6edf2ac2909ab92273a83f8f20c1e7e84e001f4f53f1a534a7488': {'0784113001': 0.0},
 '0a2de6c095c0771aa5bc2153c37938a07e7daa2bdcd159c8b534c779cb58a276': {'0660497006': 0.0},
 '0a72cba855e3b0d9723fa1742a539fca40567a1992ab1c6cfbef8713664893a9': {'0803757004': 0.0},
 '0e90161bc18662657b18dd5ed863cf5e8be27c6c6da1adabff7fbe504447eb62': {'0772005005': 0.0},
 '130d41de31ab0f530daf2408972a9cbd1f8b80bf8186144345d87f0afd32cb8e': {'0850893001': 0.0},
 '14e81f0d467b3dcea4ad85453bc0d5f998af31c0da811809a06c18f7fd5d4842': {'0516903011': 0.0},
 '154446b891fe22b1d7b7351ff4c06f08fcda2d170cb95498dcaf91612ded159a': {'0872537001': 0.0},
 '185d647c0155e22187784f8632408b4509e14c5fedebaa6105594dd86f4a3259': {'0690713010': 0.0},
 '1b41b04ebe7b0b8c3b9811e587b55f5fc2e5b383fb33331715dbf6174803b048': {'0876053002': 0.0},
 '1c843c9a9555a6715acde32dec39757cfc8562dab3009b3da71af35fedabc34a': {'0771383002': 0.0},
 '1f67c9cd04038bed60dc526f03479b380f579bdec4c5ab756496b6d9abe55dbd': {'0720125017': 0.0},
 '1f8c94995b8102bfb1fd93cd70d90d8d6d41921165dc3922ae4426c0f86b7b76': {'0681385003': 0.0},
 '2619f506d7b3d126e93212246955550735a370d8fe0bec90c4123540186a88a5': {'0529012011': 0.0},
 '278aa2097e20a94d6e505da37e41dcc5abc76b78bc27c87ea62a0e875036b610': {'0766495014': 0.0},
 '2f1055deed1fc1d2ea8da13666faeb93f6e9c8f6597e0bc8c552efab213218de': {'0806248005': 0.0},
 '2f109864d25ec1ebd3f56d7484a3551125bab7a703ab441767273c0405df62e5': {'0864928001': 0.0},
 '33f27d1a92af3c3b0564eb81650568368807875f4e7bc05ddf7510ed57fdaa16': {'0691855012': 0.0},
 '34003a0756c38058c50e8eeba4cd2c4c7af433257fa13b7d7b3faf933940a2c7': {'0651222002': 0.0},
 '3466e024e649971a9cd2c411b34fa5882648cf6a413a966ede30e53d4a69bb65': {'0708379002': 0.0},
 '35bdc9d61d688a7d5ea59011ccfe0b2ad3a2ffc77d9e007e642e94311e77bfd5': {'0692709002': 0.0},
 '35c069a2b893fe405b86c89895a00665dc74a5eee2b19b881262beae120d76ac': {'0678073001': 0.0},
 '3817b8e643dd6f66f48631dea054468744a717b07d05921c1b644103a369c901': {'0736681007': 0.0},
 '39076c14992fba0d95d6d45f22c2c503963ed8836259d83bdc6b5ecda8d6f2e7': {'0662888005': 0.0},
 '39a3eea894d4be0b571d66becb6ad9c01dfbc3d7e3aa7ba3776537e3030759c8': {'0830784001': 0.0},
 '3a5da2c16f1052476a8601a148c74a36aa2dc3733664e66d07e1e289270970a1': {'0822115004': 0.0},
 '3b4cffd4376393398d6eeafdd70bfad80d5da6bd092b7b0d9ffb5e59b5a87235': {'0609598006': 0.0},
 '3bfe7ae91681659b2bef61b5a57fde18c8e201acc1d86cadd2c36c20c0c46008': {'0568601006': 0.0},
 '3c0fb1daa5139911bc27a5172cf65811cbb0488b0759b21ea9c861c696b86526': {'0821115002': 0.0},
 '3e2ade7d50ad66e98186e9db53832848496bd86c14a58fdf96c51be282e4ca3f': {'0681916004': 0.0},
 '3e95ffa5e686bbb55acaa1f4449340e3cb8d1946d62378e67d807da4daa41679': {'0189616006': 0.0},
 '4104330b2b0b496b5b2fe94ccbb3e627c799e419bd25090db93a843aea492f65': {'0662257001': 0.0},
 '445571567813c79aedc3179baa023da67cc87452cd7031cf023f28767e0c2932': {'0739362001': 0.0},
 '4c70c9ab75cf2f718a21f4a57daf2ad2c0319b144963b95acedf4c7e833db3e9': {'0685814047': 0.0},
 '4d55bba6821c65d765df96fad06504e51e1aada172d70d43c14c0f31ed368194': {'0660726005': 0.0},
 '514d5cc00cf2c8719458da2ea3337f4167d5340a682310d7ad50123d45850739': {'0933032002': 146809.61296169728},
 '5260372611b0d7965e9e37e3fb431d6e348488bd8c7b991006eb01b30a49d370': {'0733045001': 0.0},
 '53297251042630e4725ae591a97c3b4ab40f790fd47fe1d382b49ba4867b166f': {'0768759005': 0.0},
 '5443964aedf0673793b38d78f15a4a0dfc3b64d8aa069c744a2facc0495aa784': {'0610776001': 0.0},
 '56a41440affbc7462615d0725e4c4cf8379d95f8ac9ae1d7747e3500d968306f': {'0762796004': 0.0},
 '571abc187ce8fd5c8d69faaf8094eed5ec579b3792eb667b3ebd630ebb670430': {'0823791006': 0.0},
 '58e57c3f54acfb8cdcae5939222ddc2a3e29c99dc5d8210f6df88266b6e88b9e': {'0708478001': 0.0},
 '5daca4a44cd1e355dce96a6ae0a6e483a3c92c16f89d37ebaf0e2f83671aa982': {'0516000044': 0.0},
 '5df1005c60151edc650ed79b58e7d8bbcfb6664674baeac540893ad12ef76bae': {'0826776001': 0.0},
 '62f4234f20f3a53aa5460c0b40ae1d7829b85dffd72bacce9fc7c4afb6231929': {'0711582001': 0.0},
 '65bbbae08f1bf21ac33a8c3f44b7d5e648b0cbbea35f620beceb36084e278474': {'0904545002': 0.0},
 '67048950a088bccf6b7ca8fa8b0a12a47962562f54b3a7c08474b332bb462b77': {'0396135047': 0.0},
 '678a749aacb1a5b3faedaf5bc8bc23720cbf618d2ab8d32b9536d9203e1b27e6': {'0856440001': 0.0},
 '6be4f587cdb5997111cc4401e475bb836ce2496d16617a5b1f48d97a80c62498': {'0752193001': 0.0},
 '6d8305f2a289ee508088ac1eb83f794a95f5948451ff220974ff8d93fc65ac08': {'0837941001': 0.0},
 '6dd6306381ffcaa7fe3fd08aebd5ed4d3b547175cd67ae27e2480354cae9823f': {'0610776083': 0.0},
 '6e0f8a1cb0777d7e6f10688dd0f1e6019f1281f6a54d4b30175870edc530055f': {'0569986024': 0.0},
 '6e7938c489f593b748740b62482b66cefa9cffe29739d87d48f68e8e78728eb5': {'0789909001': 0.0},
 '7b676bcb1cec4323b3dda45a48cc47c97147c41a213ec96e44fe0c90e4bb5be9': {'0672625004': 0.0},
 '7d9e67165744216311a7fdc07089d26ed916a3d54d47e628c3eb6c8765795b1c': {'0792817001': 0.0},
 '80cc7e1ed463f077046a675961a027a8ba759b9e4fdb53d74b3d97f292c332b0': {'0736218001': 0.0},
 '818d9e35537115612476357ec4d27f4d045da48a1ffb6df2d76db22540f1669f': {'0695972003': 0.0},
 '873496e698e4ebe48d8b10f456c54991de3a5364def03fd6ba4fa18ec16a4fd1': {'0596119001': 0.0},
 '885ebfa1515a85ba9feb47fa407f10c4c9611235b059fbdacfdb09042a79d7c2': {'0701229001': 0.0},
 '8d55b4ba692580d48ce270e78f368fd4231a752f1abbbb03daaecc9c62fbee25': {'0905507003': 0.0},
 '8f4d9b1db310c83fd04e5540e9eac7e90e999ec011f0caae30957069519db782': {'0741220004': 0.0},
 '91c6f4f37786556425cc8aea814a20f1a00e2fe9890d8e40b36ef4a9dcf87373': {'0685448004': 0.0},
 '930c326188de496d96e1b365b7b41b23ec36a69af600ea2ac6c216ab74a832d4': {'0529953001': 0.0},
 '99bf05e9c6f163dbb10c9d7d5c371b189dfcc33799e43f2622b03a6a13b63c90': {'0767317001': 0.0},
 '9ef729cd563ba2556d3e2585977104616761009a0f5fd3c2270640aac96e3b86': {'0575347003': 0.0},
 'a3f5ab13bbf88a2ee1c3ae809a5113ee57ceb904a4d9a9d46aa4c69f6256c1ae': {'0656065001': 0.0},
 'a41776ed1a169af3ead7c64932f3f9e7f8042c010f4668292d28ff5ba46bd01b': {'0836142001': 0.0},
 'a5230cd414c9718e1735cacc4357096914f9f36fefba8a24b94aa9f1d5699997': {'0803986011': 0.0},
 'a5266b6fbdbf55c135c21e5763c07838f213492b53c3b315121b5386ae3b1687': {'0678942037': 0.0},
 'a7b299f3f2b14efed1ff4a1dd49127627c8649183cb4635f5dee6837c36c89b0': {'0852614002': 0.0},
 'a7cbbeafe87a225affd26e94f0ce6b9b26ad9ecf101ca10fe40145daab48bf3c': {'0408647008': 0.0},
 'a7fbc1eb6472d798b95b3b742c7abb20c73a1b5b4e79a7ebfadb6b4d814cdf63': {'0759871004': 0.0},
 'a9dae6f31cd2feafc0eebe48ba236cc7fadc62287d7e7636c7699259bb3eeef4': {'0770212001': 0.0},
 'aca3fecf77c200bb6bfc69e0a5e77cfc3712d621793eee12b2ad6464853a603b': {'0554598071': 0.0},
 'adb59c69cc7e2841741c5e529292c628e1ac19d8b5ca0e078322ad335d4f70c5': {'0660308001': 0.0},
 'b379a3233c1395197c54e6ca11674b3e23a856531e01b5bf657f64ac9b93630d': {'0665817001': 0.0},
 'b409676fb35b4007967fd7ba003f2a84b7a53aaf6f6a0e66249c18d2fc4253b5': {'0866383004': 0.0},
 'b5705c172b861c6cb9a8aa14619bce17ff154341fdb10897279025cafc3da6a4': {'0787853005': 0.0},
 'b90a8270c6f10402cca365cddf1e1e9138a07ac19b2fd6b07dfeb921b91976ce': {'0465655016': 0.0},
 'ba68ce1d1637b17d342ac625cdadd9bf683bb6fa0212bc41715b2ab6da39dee5': {'0701016001': 0.0},
 'c078c63358442f65b6c0ceb302274ced4ad5528f91fc74e42390ecd0daf906bc': {'0397068012': 0.0},
 'c2f0cdda2dc3042ccd9fcd8253fd8e368769840581e40aab1d87a64ff39987e3': {'0461327001': 0.0},
 'c7e366346a0e8284ae4a7a7c49618d9240077b2bd507837ea7b732f73e394908': {'0759871025': 0.0},
 'cdcb5ae7187a23a874511becfb9dba028a1fc6ffe85c5e3bde42631574c74902': {'0678696014': 0.0},
 'cf7a1056a22451a0eb6f7dd61b925f4a886a4150e99b52b007a18d8318dfbd25': {'0734236001': 0.0},
 'd04835e523ad0a813069e0252ddbf8b70d7d841429e5d8b4e2fc90e2035f314a': {'0791587009': 0.0},
 'd39d101148eeebdf8cc0d3aaa32acd6743eb223e5bc44a2ba14dfa8aadd5fa47': {'0782874001': 0.0},
 'd7266b793a0f0d88882d68aaea54ffa1860be8168c78e21b7435631a399659e6': {'0843793001': 0.0},
 'deb45961e00f511bc24036d489e208aabb5363483389148dd42c508699586799': {'0716672018': 0.0},
 'dfe7e6ce3cde96e4545b5cf1f6c5918e6e74cc2c4a8dceb2501d2210c8997a4f': {'0695545002': 0.0},
 'e23d51b58780cc241dd4a412f72f82e0876ce41aabd97ae32622484eb6fa61ad': {'0614854008': 0.0},
 'e3fa3038af5d048ba927e93ee544b6a0fe7a14c83bfa645d7d3c3d3afef4c6e2': {'0622295001': 0.0},
 'e43d0f5e178aadbe2346eed4e6969f8352fea3851b13e941e9a17be328559ab8': {'0541519034': 0.0},
 'e78a7b0b3ef980f30305112c9aa04f6957864609f8fdef344b3abba8ae54d2d6': {'0812364005': 0.0},
 'ed6dbc458d114a5dfbd1f97e33195032b4f2d2a89dd5c81f2fea2bf78b3e7216': {'0733097008': 0.0},
 'eec7eca2db06856e95638836eecdf4860563bc4e1b20311e604b90c597badc13': {'0723349001': 0.0},
 'f4ead16535c55e2a3eb9dbea5b81da33be8dbc35c889f5122a660e5d4217b2d3': {'0681373019': 0.0},
 'f7baf8f7d0435be63c0a94b07ddfa07ab5cc2a5e133e001323a5e2d8eff0cf1c': {'0680262001': 0.0},
 'f7f39b58a1e54a8539d970280c1d177e0dde7a5840af984425e7baf8daa58618': {'0680262004': 0.0},
 'fce2a81c1f48a2f451b9a7812c85f99911221242ec9c82e4f5a3532413b11490': {'0848988001': 0.0}}

time: 36.6 ms (started: 2022-05-03 01:54:52 +00:00)

In [ ]:
df

,t_dat,customer_id,article_id,ldbw,count,count_targ,quotient
6867893,2019-03-01,f7baf8f7d0435be63c0a94b07ddfa07ab5cc2a5e133e001323a5e2d8eff0cf1c,0680262001,2019-03-01,1,0.0,0.0
20191614,2019-12-16,a5230cd414c9718e1735cacc4357096914f9f36fefba8a24b94aa9f1d5699997,0803986011,2019-12-20,1,0.0,0.0
6294079,2019-02-17,5daca4a44cd1e355dce96a6ae0a6e483a3c92c16f89d37ebaf0e2f83671aa982,0516000044,2019-02-22,1,0.0,0.0
2162782,2018-11-05,b379a3233c1395197c54e6ca11674b3e23a856531e01b5bf657f64ac9b93630d,0665817001,2018-11-09,1,0.0,0.0
21032772,2020-01-07,678a749aacb1a5b3faedaf5bc8bc23720cbf618d2ab8d32b9536d9203e1b27e6,0856440001,2020-01-10,1,0.0,0.0
21184942,2020-01-11,adb59c69cc7e2841741c5e529292c628e1ac19d8b5ca0e078322ad335d4f70c5,0660308001,2020-01-17,1,0.0,0.0
14860519,2019-07-31,eec7eca2db06856e95638836eecdf4860563bc4e1b20311e604b90c597badc13,0723349001,2019-08-02,1,0.0,0.0
17234441,2019-09-28,cdcb5ae7187a23a874511becfb9dba028a1fc6ffe85c5e3bde42631574c74902,0678696014,2019-10-04,1,0.0,0.0
24523061,2020-04-11,a7fbc1eb6472d798b95b3b742c7abb20c73a1b5b4e79a7ebfadb6b4d814cdf63,0759871004,2020-04-17,1,0.0,0.0
21039707,2020-01-07,a41776ed1a169af3ead7c64932f3f9e7f8042c010f4668292d28ff5ba46bd01b,0836142001,2020-01-10,1,0.0,0.0
3820590,2018-12-17,c2f0cdda2dc3042ccd9fcd8253fd8e368769840581e40aab1d87a64ff39987e3,0461327001,2018-12-21,1,0.0,0.0
29065452,2020-07-15,c7e366346a0e8284ae4a7a7c49618d9240077b2bd507837ea7b732f73e394908,0759871025,2020-07-17,1,0.0,0.0
12129018,2019-06-19,cf7a1056a22451a0eb6f7dd61b925f4a886a4150e99b52b007a18d8318dfbd25,0734236001,2019-06-21,1,0.0,0.0
9176547,2019-04-23,885ebfa1515a85ba9feb47fa407f10c4c9611235b059fbdacfdb09042a79d7c2,0701229001,2019-04-26,1,0.0,0.0
26336527,2020-05-26,8f4d9b1db310c83fd04e5540e9eac7e90e999ec011f0caae30957069519db782,0741220004,2020-05-29,1,0.0,0.0
11353636,2019-06-04,91c6f4f37786556425cc8aea814a20f1a00e2fe9890d8e40b36ef4a9dcf87373,0685448004,2019-06-07,1,0.0,0.0
26315640,2020-05-26,2f1055deed1fc1d2ea8da13666faeb93f6e9c8f6597e0bc8c552efab213218de,0806248005,2020-05-29,1,0.0,0.0
13694456,2019-07-11,a9dae6f31cd2feafc0eebe48ba236cc7fadc62287d7e7636c7699259bb3eeef4,0770212001,2019-07-12,1,0.0,0.0
5597463,2019-01-30,00e1fc813958a3b6b932b1eecba91895bbbeb722752c8486bee500a912125143,0736102002,2019-02-01,1,0.0,0.0
13388550,2019-07-06,0e90161bc18662657b18dd5ed863cf5e8be27c6c6da1adabff7fbe504447eb62,0772005005,2019-07-12,1,0.0,0.0
10993310,2019-05-29,6be4f587cdb5997111cc4401e475bb836ce2496d16617a5b1f48d97a80c62498,0752193001,2019-05-31,1,0.0,0.0
22741224,2020-02-26,445571567813c79aedc3179baa023da67cc87452cd7031cf023f28767e0c2932,0739362001,2020-02-28,1,0.0,0.0
8414799,2019-04-06,b90a8270c6f10402cca365cddf1e1e9138a07ac19b2fd6b07dfeb921b91976ce,0465655016,2019-04-12,1,0.0,0.0
24567714,2020-04-11,ed6dbc458d114a5dfbd1f97e33195032b4f2d2a89dd5c81f2fea2bf78b3e7216,0733097008,2020-04-17,1,0.0,0.0
7161402,2019-03-09,6e0f8a1cb0777d7e6f10688dd0f1e6019f1281f6a54d4b30175870edc530055f,0569986024,2019-03-15,1,0.0,0.0
20255535,2019-12-18,4d55bba6821c65d765df96fad06504e51e1aada172d70d43c14c0f31ed368194,0660726005,2019-12-20,1,0.0,0.0
20584658,2019-12-24,99bf05e9c6f163dbb10c9d7d5c371b189dfcc33799e43f2622b03a6a13b63c90,0767317001,2019-12-27,1,0.0,0.0
111794,2018-09-22,e3fa3038af5d048ba927e93ee544b6a0fe7a14c83bfa645d7d3c3d3afef4c6e2,0622295001,2018-09-28,1,0.0,0.0
8817704,2019-04-15,f7f39b58a1e54a8539d970280c1d177e0dde7a5840af984425e7baf8daa58618,0680262004,2019-04-19,1,0.0,0.0
14698324,2019-07-28,e23d51b58780cc241dd4a412f72f82e0876ce41aabd97ae32622484eb6fa61ad,0614854008,2019-08-02,1,0.0,0.0
26584583,2020-05-30,a7b299f3f2b14efed1ff4a1dd49127627c8649183cb4635f5dee6837c36c89b0,0852614002,2020-06-05,1,0.0,0.0
29578532,2020-07-28,3b4cffd4376393398d6eeafdd70bfad80d5da6bd092b7b0d9ffb5e59b5a87235,0609598006,2020-07-31,1,0.0,0.0
20578294,2019-12-24,6e7938c489f593b748740b62482b66cefa9cffe29739d87d48f68e8e78728eb5,0789909001,2019-12-27,1,0.0,0.0
10563939,2019-05-21,53297251042630e4725ae591a97c3b4ab40f790fd47fe1d382b49ba4867b166f,0768759005,2019-05-24,1,0.0,0.0
13010197,2019-06-30,35bdc9d61d688a7d5ea59011ccfe0b2ad3a2ffc77d9e007e642e94311e77bfd5,0692709002,2019-07-05,1,0.0,0.0
11603205,2019-06-09,e43d0f5e178aadbe2346eed4e6969f8352fea3851b13e941e9a17be328559ab8,0541519034,2019-06-14,1,0.0,0.0
30413708,2020-08-16,aca3fecf77c200bb6bfc69e0a5e77cfc3712d621793eee12b2ad6464853a603b,0554598071,2020-08-21,1,0.0,0.0
1541252,2018-10-23,2619f506d7b3d126e93212246955550735a370d8fe0bec90c4123540186a88a5,0529012011,2018-10-26,1,0.0,0.0
31400948,2020-09-11,b409676fb35b4007967fd7ba003f2a84b7a53aaf6f6a0e66249c18d2fc4253b5,0866383004,2020-09-11,1,0.0,0.0
8614937,2019-04-11,3466e024e649971a9cd2c411b34fa5882648cf6a413a966ede30e53d4a69bb65,0708379002,2019-04-12,1,0.0,0.0
443900,2018-09-29,34003a0756c38058c50e8eeba4cd2c4c7af433257fa13b7d7b3faf933940a2c7,0651222002,2018-10-05,1,0.0,0.0
13236633,2019-07-03,873496e698e4ebe48d8b10f456c54991de3a5364def03fd6ba4fa18ec16a4fd1,0596119001,2019-07-05,1,0.0,0.0
6188815,2019-02-14,a7cbbeafe87a225affd26e94f0ce6b9b26ad9ecf101ca10fe40145daab48bf3c,0408647008,2019-02-15,1,0.0,0.0
27516534,2020-06-18,d7266b793a0f0d88882d68aaea54ffa1860be8168c78e21b7435631a399659e6,0843793001,2020-06-19,1,0.0,0.0
25318952,2020-05-02,6d8305f2a289ee508088ac1eb83f794a95f5948451ff220974ff8d93fc65ac08,0837941001,2020-05-08,1,0.0,0.0
30666892,2020-08-24,0a72cba855e3b0d9723fa1742a539fca40567a1992ab1c6cfbef8713664893a9,0803757004,2020-08-28,1,0.0,0.0
26832947,2020-06-05,1b41b04ebe7b0b8c3b9811e587b55f5fc2e5b383fb33331715dbf6174803b048,0876053002,2020-06-05,1,0.0,0.0
19409592,2019-11-28,7d9e67165744216311a7fdc07089d26ed916a3d54d47e628c3eb6c8765795b1c,0792817001,2019-11-29,1,0.0,0.0
9224237,2019-04-24,3bfe7ae91681659b2bef61b5a57fde18c8e201acc1d86cadd2c36c20c0c46008,0568601006,2019-04-26,1,0.0,0.0
15612944,2019-08-18,06605e19bbc6edf2ac2909ab92273a83f8f20c1e7e84e001f4f53f1a534a7488,0784113001,2019-08-23,1,0.0,0.0
6371752,2019-02-19,ba68ce1d1637b17d342ac625cdadd9bf683bb6fa0212bc41715b2ab6da39dee5,0701016001,2019-02-22,1,0.0,0.0
153154,2018-09-23,c078c63358442f65b6c0ceb302274ced4ad5528f91fc74e42390ecd0daf906bc,0397068012,2018-09-28,1,0.0,0.0
19617693,2019-11-29,f4ead16535c55e2a3eb9dbea5b81da33be8dbc35c889f5122a660e5d4217b2d3,0681373019,2019-11-29,1,0.0,0.0
16494653,2019-09-11,56a41440affbc7462615d0725e4c4cf8379d95f8ac9ae1d7747e3500d968306f,0762796004,2019-09-13,1,0.0,0.0
758383,2018-10-05,4104330b2b0b496b5b2fe94ccbb3e627c799e419bd25090db93a843aea492f65,0662257001,2018-10-05,1,0.0,0.0
26904467,2020-06-06,a5266b6fbdbf55c135c21e5763c07838f213492b53c3b315121b5386ae3b1687,0678942037,2020-06-12,1,0.0,0.0
30891305,2020-08-29,65bbbae08f1bf21ac33a8c3f44b7d5e648b0cbbea35f620beceb36084e278474,0904545002,2020-09-04,1,0.0,0.0
2420463,2018-11-13,3e2ade7d50ad66e98186e9db53832848496bd86c14a58fdf96c51be282e4ca3f,0681916004,2018-11-16,1,0.0,0.0
10472404,2019-05-19,185d647c0155e22187784f8632408b4509e14c5fedebaa6105594dd86f4a3259,0690713010,2019-05-24,1,0.0,0.0
22744035,2020-02-26,571abc187ce8fd5c8d69faaf8094eed5ec579b3792eb667b3ebd630ebb670430,0823791006,2020-02-28,1,0.0,0.0
11402024,2019-06-05,7b676bcb1cec4323b3dda45a48cc47c97147c41a213ec96e44fe0c90e4bb5be9,0672625004,2019-06-07,1,0.0,0.0
22779133,2020-02-27,39a3eea894d4be0b571d66becb6ad9c01dfbc3d7e3aa7ba3776537e3030759c8,0830784001,2020-02-28,1,0.0,0.0
21824124,2020-01-30,4c70c9ab75cf2f718a21f4a57daf2ad2c0319b144963b95acedf4c7e833db3e9,0685814047,2020-01-31,1,0.0,0.0
2248261,2018-11-08,39076c14992fba0d95d6d45f22c2c503963ed8836259d83bdc6b5ecda8d6f2e7,0662888005,2018-11-09,1,0.0,0.0
10294636,2019-05-16,1f8c94995b8102bfb1fd93cd70d90d8d6d41921165dc3922ae4426c0f86b7b76,0681385003,2019-05-17,1,0.0,0.0
20122676,2019-12-14,5df1005c60151edc650ed79b58e7d8bbcfb6664674baeac540893ad12ef76bae,0826776001,2019-12-20,1,0.0,0.0
23871524,2020-03-30,3c0fb1daa5139911bc27a5172cf65811cbb0488b0759b21ea9c861c696b86526,0821115002,2020-04-03,1,0.0,0.0
10104288,2019-05-11,58e57c3f54acfb8cdcae5939222ddc2a3e29c99dc5d8210f6df88266b6e88b9e,0708478001,2019-05-17,1,0.0,0.0
10587738,2019-05-21,dfe7e6ce3cde96e4545b5cf1f6c5918e6e74cc2c4a8dceb2501d2210c8997a4f,0695545002,2019-05-24,1,0.0,0.0
20527189,2019-12-23,5260372611b0d7965e9e37e3fb431d6e348488bd8c7b991006eb01b30a49d370,0733045001,2019-12-27,1,0.0,0.0
25644308,2020-05-12,3817b8e643dd6f66f48631dea054468744a717b07d05921c1b644103a369c901,0736681007,2020-05-15,1,0.0,0.0
28840394,2020-07-10,33f27d1a92af3c3b0564eb81650568368807875f4e7bc05ddf7510ed57fdaa16,0691855012,2020-07-10,1,0.0,0.0
26443764,2020-05-28,5443964aedf0673793b38d78f15a4a0dfc3b64d8aa069c744a2facc0495aa784,0610776001,2020-05-29,1,0.0,0.0
24838105,2020-04-20,130d41de31ab0f530daf2408972a9cbd1f8b80bf8186144345d87f0afd32cb8e,0850893001,2020-04-24,1,0.0,0.0
14418498,2019-07-24,80cc7e1ed463f077046a675961a027a8ba759b9e4fdb53d74b3d97f292c332b0,0736218001,2019-07-26,1,0.0,0.0
3307342,2018-12-02,67048950a088bccf6b7ca8fa8b0a12a47962562f54b3a7c08474b332bb462b77,0396135047,2018-12-07,1,0.0,0.0
25932993,2020-05-19,2f109864d25ec1ebd3f56d7484a3551125bab7a703ab441767273c0405df62e5,0864928001,2020-05-22,1,0.0,0.0
22855518,2020-02-29,3a5da2c16f1052476a8601a148c74a36aa2dc3733664e66d07e1e289270970a1,0822115004,2020-03-06,1,0.0,0.0
31628043,2020-09-18,514d5cc00cf2c8719458da2ea3337f4167d5340a682310d7ad50123d45850739,0933032002,2020-09-18,1,1.0,1.0
30472817,2020-08-18,8d55b4ba692580d48ce270e78f368fd4231a752f1abbbb03daaecc9c62fbee25,0905507003,2020-08-21,1,0.0,0.0
30578276,2020-08-21,6dd6306381ffcaa7fe3fd08aebd5ed4d3b547175cd67ae27e2480354cae9823f,0610776083,2020-08-21,1,0.0,0.0
21082098,2020-01-08,d39d101148eeebdf8cc0d3aaa32acd6743eb223e5bc44a2ba14dfa8aadd5fa47,0782874001,2020-01-10,1,0.0,0.0
222477,2018-09-25,3e95ffa5e686bbb55acaa1f4449340e3cb8d1946d62378e67d807da4daa41679,0189616006,2018-09-28,1,0.0,0.0
19578381,2019-11-29,b5705c172b861c6cb9a8aa14619bce17ff154341fdb10897279025cafc3da6a4,0787853005,2019-11-29,1,0.0,0.0
28881520,2020-07-11,278aa2097e20a94d6e505da37e41dcc5abc76b78bc27c87ea62a0e875036b610,0766495014,2020-07-17,1,0.0,0.0
23899395,2020-03-30,fce2a81c1f48a2f451b9a7812c85f99911221242ec9c82e4f5a3532413b11490,0848988001,2020-04-03,1,0.0,0.0
1887921,2018-10-29,818d9e35537115612476357ec4d27f4d045da48a1ffb6df2d76db22540f1669f,0695972003,2018-11-02,1,0.0,0.0
106192,2018-09-22,930c326188de496d96e1b365b7b41b23ec36a69af600ea2ac6c216ab74a832d4,0529953001,2018-09-28,1,0.0,0.0
559678,2018-09-30,14e81f0d467b3dcea4ad85453bc0d5f998af31c0da811809a06c18f7fd5d4842,0516903011,2018-10-05,1,0.0,0.0
28518866,2020-07-03,0a2de6c095c0771aa5bc2153c37938a07e7daa2bdcd159c8b534c779cb58a276,0660497006,2020-07-03,1,0.0,0.0
30217693,2020-08-11,deb45961e00f511bc24036d489e208aabb5363483389148dd42c508699586799,0716672018,2020-08-14,1,0.0,0.0
26507672,2020-05-29,62f4234f20f3a53aa5460c0b40ae1d7829b85dffd72bacce9fc7c4afb6231929,0711582001,2020-05-29,1,0.0,0.0
29923719,2020-08-04,d04835e523ad0a813069e0252ddbf8b70d7d841429e5d8b4e2fc90e2035f314a,0791587009,2020-08-07,1,0.0,0.0
23471347,2020-03-16,e78a7b0b3ef980f30305112c9aa04f6957864609f8fdef344b3abba8ae54d2d6,0812364005,2020-03-20,1,0.0,0.0
31221725,2020-09-07,154446b891fe22b1d7b7351ff4c06f08fcda2d170cb95498dcaf91612ded159a,0872537001,2020-09-11,1,0.0,0.0
3425637,2018-12-06,35c069a2b893fe405b86c89895a00665dc74a5eee2b19b881262beae120d76ac,0678073001,2018-12-07,1,0.0,0.0
1790744,2018-10-27,a3f5ab13bbf88a2ee1c3ae809a5113ee57ceb904a4d9a9d46aa4c69f6256c1ae,0656065001,2018-11-02,1,0.0,0.0
26259425,2020-05-25,1c843c9a9555a6715acde32dec39757cfc8562dab3009b3da71af35fedabc34a,0771383002,2020-05-29,1,0.0,0.0
25512638,2020-05-08,9ef729cd563ba2556d3e2585977104616761009a0f5fd3c2270640aac96e3b86,0575347003,2020-05-08,1,0.0,0.0
18999981,2019-11-16,1f67c9cd04038bed60dc526f03479b380f579bdec4c5ab756496b6d9abe55dbd,0720125017,2019-11-22,1,0.0,0.0

time: 46.4 ms (started: 2022-05-03 01:31:27 +00:00)

In [ ]:
target_sales = df.drop('customer_id', axis=1).groupby('article_id')['quotient'].sum()
general_pred = target_sales.nlargest(N).index.tolist()

time: 11.9 ms (started: 2022-05-03 01:31:30 +00:00)

In [ ]:
target_sales

article_id
0189616006    0.0
0396135047    0.0
0397068012    0.0
0408647008    0.0
0461327001    0.0
0465655016    0.0
0516000044    0.0
0516903011    0.0
0529012011    0.0
0529953001    0.0
0541519034    0.0
0554598071    0.0
0568601006    0.0
0569986024    0.0
0575347003    0.0
0596119001    0.0
0609598006    0.0
0610776001    0.0
0610776083    0.0
0614854008    0.0
0622295001    0.0
0651222002    0.0
0656065001    0.0
0660308001    0.0
0660497006    0.0
0660726005    0.0
0662257001    0.0
0662888005    0.0
0665817001    0.0
0672625004    0.0
0678073001    0.0
0678696014    0.0
0678942037    0.0
0680262001    0.0
0680262004    0.0
0681373019    0.0
0681385003    0.0
0681916004    0.0
0685448004    0.0
0685814047    0.0
0690713010    0.0
0691855012    0.0
0692709002    0.0
0695545002    0.0
0695972003    0.0
0701016001    0.0
0701229001    0.0
0708379002    0.0
0708478001    0.0
0711582001    0.0
0716672018    0.0
0720125017    0.0
0723349001    0.0
0733045001    0.0
0733097008    0.0
0734236001    0.0
0736102002    0.0
0736218001    0.0
0736681007    0.0
0739362001    0.0
0741220004    0.0
0752193001    0.0
0759871004    0.0
0759871025    0.0
0762796004    0.0
0766495014    0.0
0767317001    0.0
0768759005    0.0
0770212001    0.0
0771383002    0.0
0772005005    0.0
0782874001    0.0
0784113001    0.0
0787853005    0.0
0789909001    0.0
0791587009    0.0
0792817001    0.0
0803757004    0.0
0803986011    0.0
0806248005    0.0
0812364005    0.0
0821115002    0.0
0822115004    0.0
0823791006    0.0
0826776001    0.0
0830784001    0.0
0836142001    0.0
0837941001    0.0
0843793001    0.0
0848988001    0.0
0850893001    0.0
0852614002    0.0
0856440001    0.0
0864928001    0.0
0866383004    0.0
0872537001    0.0
0876053002    0.0
0904545002    0.0
0905507003    0.0
0933032002    1.0
Name: quotient, dtype: float64

time: 30.9 ms (started: 2022-05-03 01:31:36 +00:00)

In [ ]:
general_pred

['0933032002',
 '0189616006',
 '0396135047',
 '0397068012',
 '0408647008',
 '0461327001',
 '0465655016',
 '0516000044',
 '0516903011',
 '0529012011',
 '0529953001',
 '0541519034']

time: 11.4 ms (started: 2022-05-03 01:31:39 +00:00)

In [ ]:
df

,t_dat,customer_id,article_id,ldbw,count,count_targ,quotient
28106107,2020-06-26,7297b62b68c0d6faa75ee8259c434ffaedb6c8a5e07a4351598585b03ddc72ea,0809874004,2020-06-30,1,0.0,0.0
7910460,2019-03-27,bbc9cdebf8b438a71e709344d9035875de20166eb2ad6ccccaee804067965980,0554541023,2019-04-02,1,0.0,0.0
24478253,2020-04-11,6097f814a501fe9dac608d9588a964d15b0ca60ee0b5582913754619db4d7cbc,0562245025,2020-04-14,1,0.0,0.0
617508,2018-10-01,966cfe4219dba8e8e417349b0334a2c12c7613114b1a40595060bc993a7d467a,0645065015,2018-10-02,1,0.0,0.0
13171581,2019-07-02,9ab19956caaad5c8c9c32d5ec9a3591430e6a051bc01857a9a26edb61c68d7dc,0663282007,2019-07-02,1,0.0,0.0
10360109,2019-05-16,caa84f328f347d9d53b1a3847c2f025440783c4d07520669ca8ef67bd5e7cdbc,0733090001,2019-05-21,1,0.0,0.0
26790296,2020-06-04,3deaa9bebdb621fad5d41a6ad6ee08706fb74c520ef25df05c04c01f28f94ff5,0859125006,2020-06-09,1,0.0,0.0
22379109,2020-02-15,6b0f0f251df4e5b3e2115839d4ab230ad610f048e8d0c4c78a7369b010bfe4bd,0820431001,2020-02-18,1,0.0,0.0
16820614,2019-09-20,8aa8d4da9895493deac5194982b88df256b6905632a9fe25fee561ae3f51884f,0297078001,2019-09-24,1,0.0,0.0
14845368,2019-07-31,a78ff3279f3434671c2d6417627bfa84c09e7ae03f1d002a09a36a0a175b4e12,0556260008,2019-08-06,1,0.0,0.0
14123056,2019-07-19,bd190183d6a572b6375b3f64070e09e2d84b8d9b6646fbcfd35c7c9e9945a626,0793911001,2019-07-23,1,0.0,0.0
3258115,2018-11-30,dce7b7e8f5dc2d883105d2f31151bec497cbff60a9f93dfa748c1809ec0ee18b,0554450027,2018-12-04,1,0.0,0.0
3433637,2018-12-06,6de7905fa29c91c3bb92b71b2e5aa8b497d6d5b25b6f07288bbf2457f115c061,0690623002,2018-12-11,1,0.0,0.0
16601053,2019-09-14,4bd2fb3334cb495a5254e57222b2479e7c0b1d7cc027726c4e0ddf70b17ea1ad,0603145001,2019-09-17,1,0.0,0.0
816552,2018-10-06,e377f61e01e3aa577d521a5812c9d0313c69ad367d51e019f06f2d915e1960e0,0585342001,2018-10-09,1,0.0,0.0
21909602,2020-02-01,a615071187e7c6684f4c973973bc682625bc4fa5b6a573446faf2b253134a350,0789309003,2020-02-04,1,0.0,0.0
358010,2018-09-28,265fe289cfbad0458fca73a3d295c4f8167531907b407333fe9cfb7c3b5d1a5d,0635084001,2018-10-02,1,0.0,0.0
25713580,2020-05-13,f8fff869a9f27fd5a75d293f474b88c27f046d234273fcdcdff24e295a53c53c,0703991001,2020-05-19,1,0.0,0.0
17559071,2019-10-05,5b3d8d1cd30217316e38220301aa57dc501158e60ab363e3536d54033d6ff1f0,0369796007,2019-10-08,1,0.0,0.0
23777317,2020-03-27,5a7ba494dd8f4ffe0857ee5241390758f269f9bd6bc0671073e1c31ea5930e3a,0714790017,2020-03-31,1,0.0,0.0
22393471,2020-02-15,cb88182baae9425b725ac4d1947d3ff49b94b576c0bb333a4f931932cb324e81,0810838010,2020-02-18,1,0.0,0.0
2576684,2018-11-17,92f8276d89d58cd750ed97946754506c98d2c43ab8c682f2ed2ab65cf1ba8c29,0554546014,2018-11-20,1,0.0,0.0
196357,2018-09-24,a7af1fcea4eb655332abea96d156d476fc13f679b3f5d2632a68b0d1f1f38465,0355072002,2018-09-25,1,0.0,0.0
19737811,2019-12-01,b23d32a6e3b9961395f8a93a6b55011dfec18bebd15baa599b48b05d5b25bb21,0562245088,2019-12-03,1,0.0,0.0
10886051,2019-05-27,6fa37f855d7b4d69e3f402b730f7c8ae7697e62f802264a417b8c26463b45019,0380609001,2019-05-28,1,0.0,0.0
21510296,2020-01-21,f7f69c3ad6380619a179167c498833c426e97e13f02b4409ea4ed1a2d581e869,0189634001,2020-01-21,1,0.0,0.0
30475185,2020-08-18,9fd3dbd9b5b07e253204365a40509424f9c5a6eb4a8596547a1f93c4a61cf46c,0760084015,2020-08-18,1,0.0,0.0
2247280,2018-11-08,306f7d4cda0015d8c426403fe8c2c3566a40ae12a17840cfb8e0fadb6a375094,0634426008,2018-11-13,1,0.0,0.0
15513728,2019-08-15,d5858b143c7a41040e8b043850dc8446e5d2332f54cd9342f64203a3cbc5c1b6,0733027006,2019-08-20,1,0.0,0.0
29152148,2020-07-17,b16553b09829e9209f86a9841103820816084ab75bdc4eb6a57e048a32f143c5,0865490003,2020-07-21,1,0.0,0.0
12106502,2019-06-19,97b67fbe22a99521a1c265747356da6c8f761281dd772dc7aadbf28e42def6a3,0692745006,2019-06-25,1,0.0,0.0
11488054,2019-06-07,24bde2de30717d732f04d88bb76b06ec32170b6e4832859cbc586baaf78f9ea1,0698260005,2019-06-11,1,0.0,0.0
13611129,2019-07-10,4bd33ee9bbbcfaecfdd73b4d831fb6b4d26f5a7ff3ed9937aec7a2bc4014f6ee,0217727002,2019-07-16,1,0.0,0.0
7951406,2019-03-28,9afdd1bd110fef3eea5afc99a0628720c3b8f0926f710ec2719339de0d261abc,0659832004,2019-04-02,1,0.0,0.0
18736691,2019-11-07,3d0f014b3884ca7399daaf73f097c89548bdbca7f6c41b30db8142aff9c1de7e,0775624001,2019-11-12,1,0.0,0.0
11115954,2019-05-31,8182ec199a611bf191679a1e9cb149c2a33530a4051d2b719f0462aa404b13b7,0717490010,2019-06-04,1,0.0,0.0
5356840,2019-01-24,6c1628b9fa0eb78392062383ebc026f081ac260514ef0448e8b886339b4d2833,0671949002,2019-01-29,1,0.0,0.0
20262339,2019-12-18,66ce293ec2c21960d4bb91e4ea21c53ce3f856c89d9af8438454dab5165e77ca,0801309010,2019-12-24,1,0.0,0.0
24666129,2020-04-14,bfedc4b1f450cc1159dd951e6ee575b9934b72fba2a2b4e276c64703962b6a2b,0840360002,2020-04-14,1,0.0,0.0
11117818,2019-05-31,87acc56b1323fed2e2e769f2cbe3871e793e23811795abbd154e72904088516f,0700701003,2019-06-04,1,0.0,0.0
19955289,2019-12-08,906e5af04f9fda55a802a1082860ba4f6b41af5e0b30ba676b2ff9a90169b073,0685816022,2019-12-10,1,0.0,0.0
19120665,2019-11-20,973958a9d84ab872b35037124845597ebe6cb4b8950ed3bc8929b76be9826963,0792817003,2019-11-26,1,0.0,0.0
13358090,2019-07-05,85d7a93b6c60ccaf790d04b1fa75ed9a73688df7969d6748be845dab10ceacad,0578317003,2019-07-09,1,0.0,0.0
8702147,2019-04-13,455148075ff7628dc5c8d261aee3464dc5cf466fc3e8d7c53dc7c8f37752caf6,0578816002,2019-04-16,1,0.0,0.0
1337397,2018-10-18,38eaf8f5385bac19bce7f1e34cd6ff4281b11f7ea32771792098943a7d511557,0636323001,2018-10-23,1,0.0,0.0
16717443,2019-09-17,b43b853cee49dffc65dfb2f7fbb54e8b96cdb8610634fc2bc7eea87cda8a6874,0783310001,2019-09-17,1,0.0,0.0
17738050,2019-10-09,b8ceea068bf062097b108458548b2818153c15b3102633ecb17d03017487916b,0764624005,2019-10-15,1,0.0,0.0
5637716,2019-01-31,0908ead6b125e9a6e332f9c6867dbdd5b395721e13317bfff375a87de79a1c57,0651905005,2019-02-05,1,0.0,0.0
4066555,2018-12-22,93b3151dd3e5c329fb7acc4b82ac58b848445f4de2ea83b389cb22d60fe9e091,0727633001,2018-12-25,1,0.0,0.0
2722829,2018-11-21,763d84ba6e9fc60acdaf01f390898c7b78d41aa6c0a7fada86304025f3f4d107,0640807002,2018-11-27,1,0.0,0.0
15003850,2019-08-04,2511d71d29bf2880629830c7555cd448fdfcf9864bf87ef20567712c267d9b43,0695421001,2019-08-06,1,0.0,0.0
11112753,2019-05-31,759d576d8db75addb26fa2e83c504e6a383fcbd7b28c158351957cd8b007f861,0628927001,2019-06-04,1,0.0,0.0
3436118,2018-12-06,7e83af6a4f48a7f1f7a09c2650fc6febeb6ebe8018df074a03666393864dbd96,0571860004,2018-12-11,1,0.0,0.0
9021202,2019-04-20,30e616a2820292560b671f624e3a1cb255acd4622e5e525e0dd04a3ce4703013,0727029001,2019-04-23,1,0.0,0.0
11385208,2019-06-05,2955c344b144a520c2adeafb3cab1c11d1296a9ec5a7a79f4414db34615a78e7,0777473001,2019-06-11,1,0.0,0.0
2100918,2018-11-03,cc07ee278241f60d0a1da583b886fc7f8eba7f1320dfb80aa8212dd44800b5ff,0676141001,2018-11-06,1,0.0,0.0
9068631,2019-04-21,18e99828d44c280c69bccf8722241a8cbe1c777a8002ec85d1912b7860b94723,0707743006,2019-04-23,1,0.0,0.0
28486244,2020-07-02,750a757d849086523dd1db04215abf1eb1fc519e138f5fa90448d09afa24f0b5,0711053005,2020-07-07,1,0.0,0.0
23749610,2020-03-26,8c063ebe26ae4cd68f62276e6506387a9cc0779cb879480cd0f8eb8a1c2b8bb3,0824997001,2020-03-31,1,0.0,0.0
10556987,2019-05-21,2baf8bb39900e52416dab7d24ef40c07a54c7cb4d9638a4cf993b2852b5a9e84,0559634023,2019-05-21,1,0.0,0.0
26582857,2020-05-30,a0190169f8030e474aab2bebbeedbe8fea2c56a03c21a74ba5e660989c0a0424,0806248005,2020-06-02,1,0.0,0.0
18300037,2019-10-26,196263d026297c5e3eb6a258bb05bc2fde38fa91cfcd86266d721c5f4d9b8d4d,0664746002,2019-10-29,1,0.0,0.0
27485947,2020-06-18,79e5bc60c9da329d2ce8ea4a8ae880236e606183ebc7610bbad5391baf940e98,0840947003,2020-06-23,1,0.0,0.0
31284548,2020-09-08,c6b0278ada5a3ba61571fb0abf4f859116cb5b6e8e80609999dd0e5cc958164c,0694848001,2020-09-08,1,1.0,1.0
19625371,2019-11-30,030db135f08e8d3235f84656a24edb5938b5f04de085afc88c4ae5875d1fbf25,0738943001,2019-12-03,1,0.0,0.0
18475372,2019-10-31,7e6af8102d25cdcaa058df763bf8e9c7171fe10ceeb9380138da06bf2f2a7f6d,0788946001,2019-11-05,1,0.0,0.0
11079814,2019-05-30,fc3036855c72eb1fb6c2384284dfe2fdaa77f11bbfd0e616606158103fdf0d51,0744893003,2019-06-04,1,0.0,0.0
19604651,2019-11-29,e075e59f580e9734a6b27670f583e41adf4f2298de9f0ced97d323e8e7abe308,0679853013,2019-12-03,1,0.0,0.0
30074623,2020-08-07,d1d72d1d27cd88dc5bf362aa6090dd294466a751bf9c921fffc06743b7b93150,0714790021,2020-08-11,1,0.0,0.0
30734553,2020-08-25,c0db3e9e4f7d481b2d0e39d99db1d8b59de1f719ccad9028b1fbb5c850f3cc60,0811644004,2020-08-25,1,0.0,0.0
17464499,2019-10-03,4fa6d573a302311f7e0478fd31dab8dfef0bf7ecff66b897c48013d43dfb4a6c,0772764001,2019-10-08,1,0.0,0.0
26535426,2020-05-29,db19a3bb425868da63073aadf7acd0ca14c0b03dc4574761891dd2296bc4b7c7,0817477002,2020-06-02,1,0.0,0.0
30490845,2020-08-19,1183ce9f9850191a027a04bc44ac7fb996d45edc7ad26e0b9edf88ab81cf01ce,0721990001,2020-08-25,1,0.0,0.0
14572801,2019-07-26,80a917e63aa985aab583a91f15d0142bfc5622fc0ab50be9f1293542e9e314ce,0605106007,2019-07-30,1,0.0,0.0
28725922,2020-07-07,b73cc00f4cbfd812c22461a46661ca7c6f212b0f85493f0a8c8865b5fdaa030f,0839332003,2020-07-07,1,0.0,0.0
6473819,2019-02-21,d52aa5da183e58da4449c656922b39e4cd0826ed9564641e297903c5db1872cc,0615182009,2019-02-26,1,0.0,0.0
6342255,2019-02-18,d6a02a9748b4fdf87236223819ef7ec603da77b71451eaa9a48c46d236d77816,0542402001,2019-02-19,1,0.0,0.0
25449152,2020-05-07,0578e5553c27949dad5d742123c531d5cf8bd08357345a23244cda525adcd987,0791587009,2020-05-12,1,0.0,0.0
31015716,2020-09-01,ac189021fa98f3d2c790bf0035c4c52af276556a352d96e5b6f71abb48d23ca0,0521062009,2020-09-01,1,0.0,0.0
5212829,2019-01-20,96e2720e1d431bbeff75410666f23062404060b0030992aaafee86a4603f2c14,0716014002,2019-01-22,1,0.0,0.0
14306666,2019-07-23,3dc9c7eaae2ead3e1642fde18deedd36725314c4e23a87f54b5692deedcbfbac,0752020002,2019-07-23,1,0.0,0.0
6774820,2019-02-27,c0463612fa59bfb8b45c9aed9e6a801f03bda1381ab979597eb7a98d1cca22e4,0664074021,2019-03-05,1,0.0,0.0
6987165,2019-03-05,598cb7314962498be4c5797b48c44b1bda3989483f4c7d278cbdd4f19c05b71b,0610776028,2019-03-05,1,0.0,0.0
16718889,2019-09-17,be987afadabaf39a8ee0c814a0dd8e4efe6759edf2be0d02bb354d4951b85bc4,0663034005,2019-09-17,1,0.0,0.0
28579985,2020-07-04,41da840fb435dc6e587f6b654f7c96e2c66217727333c2a6e210d9819d0b14a1,0766346004,2020-07-07,1,0.0,0.0
9591475,2019-05-01,03f860341d5a441090e0834a730fb3ad674600b06c97f71971060a96c86df48a,0739476001,2019-05-07,1,0.0,0.0
12681650,2019-06-26,03569ca08b8cad0dd3cdcb6d05c1ab82e39bbb81f4e4447d7e1784ce203704f5,0301656013,2019-07-02,1,0.0,0.0
11371505,2019-06-04,e86dcd9d523b82990de18cc959d86e0bd66e373c0c518c40c714f029a9d7c0f2,0610776028,2019-06-04,1,0.0,0.0
21195547,2020-01-11,fc4b71f650d6805739b898b6e118d2f29150c1d48900a5666891603d503deb9b,0562245093,2020-01-14,1,0.0,0.0
30270328,2020-08-12,a9f7afb19c8222d80e1ec0793c1f3eefe7d7e572c0001ae0498b56512e69b09a,0832458002,2020-08-18,1,0.0,0.0
3453803,2018-12-06,f781f16ec2d3b23139031f78255442520176bfc2cc6d73647c33eea4cc9b0cf7,0571436030,2018-12-11,1,0.0,0.0
10198331,2019-05-13,ed79cad3b33e51b8a1a9e6dfd41c8d87ed109c3412bb172a35aa2730792dae92,0689564001,2019-05-14,1,0.0,0.0
15502710,2019-08-15,9f1c79d8a290ee19464587ef7eb81070cb456bcdd9a716fd8ae80744baaea9fa,0727004001,2019-08-20,1,0.0,0.0
29592562,2020-07-28,891f94fefa1c4c8a39e10413fb485681397df0267f1bba550573b8ed118ca2a7,0523490005,2020-07-28,1,0.0,0.0
25339364,2020-05-03,29fa1c132794dc2c7c6e22998f3822029bd2d7669f093d84b14aeb68b91eec6e,0870290001,2020-05-05,1,0.0,0.0
23638701,2020-03-23,0e27d24b31a279c3ecc6e03a8018b6154c86167281e9702890777f6411cdb825,0820526005,2020-03-24,1,0.0,0.0
19427260,2019-11-28,a7d4d5b061b289f9c6cebd244ed4e0040269f1051332f3459109f3f8e290e24b,0615141002,2019-12-03,1,0.0,0.0
20120777,2019-12-14,4f558da7112f1ebdd86601a724592a4bb7aee9276dd26eee4c5f5539c4168599,0783707047,2019-12-17,1,0.0,0.0
2991720,2018-11-24,9692da29835d12a4ee9c2000099efb8aff0791fd5ca205c96859057b85d97f07,0578876002,2018-11-27,1,0.0,0.0
25320594,2020-05-02,7b668ad1be1f9ff7e6c1d510d4e91d84ab71c475b72cd0d112e821ec0cf35744,0860819001,2020-05-05,1,0.0,0.0

time: 195 ms (started: 2022-05-03 01:23:38 +00:00)

## Trending

In [ ]:
import pandas as pd
import numpy as np
from math import sqrt
from pathlib import Path
from tqdm import tqdm
tqdm.pandas()

N = 12

time: 26.2 ms (started: 2022-05-02 11:07:09 +00:00)

In [ ]:
# df_trans = pd.read_csv('/kaggle/input/h-and-m-personalized-fashion-recommendations/transactions_train.csv',dtype={'article_id': str})
df_trans = pd.read_csv("/content/drive/MyDrive/CSCI_567_ML/Data/transactions_train.csv",dtype={'article_id': str})

time: 45.2 s (started: 2022-05-02 01:55:02 +00:00)

In [ ]:
df_trans['t_dat'] = pd.to_datetime(df_trans['t_dat'])

time: 3.28 s (started: 2022-05-02 01:55:47 +00:00)

In [ ]:
# Step1
# ldbw = last day of billing week

df = df_trans[['t_dat', 'customer_id', 'article_id']].copy()
last_ts = df['t_dat'].max()
df['ldbw'] = df['t_dat'].apply(lambda d: last_ts - (last_ts - d).floor('7D')) #~50 mins to exec this line
weekly_sales = df.drop('customer_id', axis=1).groupby(['ldbw', 'article_id']).count()
weekly_sales = weekly_sales.rename(columns={'t_dat': 'count'})
df = df.join(weekly_sales, on=['ldbw', 'article_id'])
weekly_sales = weekly_sales.reset_index().set_index('article_id')
last_day = last_ts.strftime('%Y-%m-%d')

df = df.join(
    weekly_sales.loc[weekly_sales['ldbw']==last_day, ['count']],
    on='article_id', rsuffix="_targ")

df['count_targ'].fillna(0, inplace=True)
del weekly_sales
df['quotient'] = df['count_targ'] / df['count']

purchase_dict = {}
#~35 mins for the loop
for i in tqdm(df.index):
    cust_id = df.at[i, 'customer_id']
    art_id = df.at[i, 'article_id']
    t_dat = df.at[i, 't_dat']

    if cust_id not in purchase_dict:
        purchase_dict[cust_id] = {}

    if art_id not in purchase_dict[cust_id]:
        purchase_dict[cust_id][art_id] = 0
    
    x = max(1, (last_ts - t_dat).days)

    a, b, c, d = 2.5e4, 1.5e5, 2e-1, 1e3
    y = a / np.sqrt(x) + b * np.exp(-c*x) - d

    value = df.at[i, 'quotient'] * max(0, y)
    purchase_dict[cust_id][art_id] += value

target_sales = df.drop('customer_id', axis=1).groupby('article_id')['quotient'].sum()
general_pred = target_sales.nlargest(N).index.tolist()

100%|ââââââââââ| 31788324/31788324 [42:07<00:00, 12575.24it/s]

time: 1h 33min 50s (started: 2022-05-02 01:57:09 +00:00)

In [ ]:
print(len(purchase_dict))

1362281
time: 1.17 ms (started: 2022-05-02 05:12:29 +00:00)

In [ ]:
# Step2 & Step3

pairs = np.load('/content/drive/MyDrive/CSCI_567_ML/Data/pairs_cudf.npy',allow_pickle=True).item()
sub = pd.read_csv('/content/drive/MyDrive/CSCI_567_ML/Data/sample_submission.csv')

# ~15 mins
pred_list = []
for cust_id in tqdm(sub['customer_id']):
    if cust_id in purchase_dict:
        series = pd.Series(purchase_dict[cust_id])
        series = series[series > 150]
        l = series.nlargest(N).index.tolist()
        tmp_l = l.copy()
        for elm in tmp_l:
            if len(l) < N and int(elm) in pairs.keys():
                itm = pairs[int(elm)]
                l.append('0' + str(itm))
        if len(l) < N:
            l = l + general_pred[:(N-len(l))]
    else:
        l = general_pred
    pred_list.append(' '.join(l))

sub['prediction'] = pred_list

100%|ââââââââââ| 1371980/1371980 [14:21<00:00, 1592.96it/s]

time: 14min 27s (started: 2022-05-02 05:12:46 +00:00)

In [ ]:
sub.to_csv('/content/drive/MyDrive/CSCI_567_ML/sub.csv',index=False)
sub.to_csv(f'submission.csv',index=False)

time: 13.4 s (started: 2022-05-02 05:27:14 +00:00)

In [ ]:
sub = pd.read_csv('/content/drive/MyDrive/CSCI_567_ML/sub.csv')

time: 2.07 s (started: 2022-05-02 01:54:35 +00:00)

## Submission

In [ ]:
sub.head()

In [ ]:
if len(sub) != 1371980:
  print("Length not right")
print(len(sub))

1371980
time: 1.52 ms (started: 2022-05-02 05:27:28 +00:00)

In [ ]:
#Export csv and submit
sub.head()

,customer_id,prediction
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,0568601043 0568601006 0568601006 0568597006 04...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,0826211002 0800436010 0739590027 0706016001 06...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0794321007 0852643001 0852643003 0858883002 07...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,0448509014 0573085028 0751471001 0706016001 06...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,0730683050 0791587015 0896152002 0818320001 09...

time: 7.67 ms (started: 2022-05-02 05:27:42 +00:00)

In [ ]:
# submission code
# Submission must have 1371980 rows
!kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f submission.csv -m "Zeeshan submission"

100% 258M/258M [00:07<00:00, 34.7MB/s]
Successfully submitted to H&M Personalized Fashion Recommendationstime: 9.71 s (started: 2022-05-02 05:27:54 +00:00)